Repository codesquad-members-2021/airbnb, pull requests merged in 2021-05, with the labels that each got.

#1 [ team-11 / FE ] MainPage디자인 & SearchBar 일부기능 (05.19 추가)
  FE/.gitignore
  FE/README.md
  FE/package-lock.json
  FE/package.json
  FE/public/index.html
  FE/public/manifest.json
  FE/public/robots.txt
  FE/src/App.js
  FE/src/App.test.js
  FE/src/components/Footer/AnyWhere.jsx
  FE/src/components/Footer/Floor.jsx
  FE/src/components/Footer/Footer.jsx
  FE/src/components/Footer/NearTravel.jsx
  FE/src/components/GlobalStyle.jsx
  FE/src/components/Header/Header.jsx
  FE/src/components/Header/Logo.jsx
  FE/src/components/Header/Menu.jsx
  FE/src/components/Header/MyPage.jsx
  FE/src/components/Main.jsx
  FE/src/components/SearchBar/CloseButton.jsx
  FE/src/components/SearchBar/Period/Calendar/Calendar.jsx
  FE/src/components/SearchBar/Period/Calendar/Day.jsx
  FE/src/components/SearchBar/Period/CalendarModal.jsx
  FE/src/components/SearchBar/Period/Period.jsx
  FE/src/components/SearchBar/Personnel/Personnel.jsx
  FE/src/components/SearchBar/Personnel/PersonnelModal.jsx
  FE/src/components/SearchBar/Price/Price.jsx
  FE/src/components/SearchBar/SearchBar.jsx
  FE/src/components/SearchBar/SearchButton.jsx
  FE/src/index.css
  FE/src/index.js
  FE/src/reportWebVitals.js
  FE/src/setupTests.js
Labels: review-fe

#2 [ team-03 / FE ] airbnb 메인 정적 ui 구성 및 캘린더 구현
  BE/.gitignore
  FE/client/.eslintrc
  FE/client/.gitignore
  FE/client/README.md
  FE/client/package.json
  FE/client/public/favicon.ico
  FE/client/public/index.html
  FE/client/src/App.tsx
  FE/client/src/Components/GNB/index.tsx
  FE/client/src/Components/Modal/Calendar.tsx
  FE/client/src/Components/Modal/ChargeModal.tsx
  FE/client/src/Components/Modal/Month.tsx
  FE/client/src/Components/Modal/PersonnelModal.tsx
  FE/client/src/Components/Modal/index.tsx
  FE/client/src/Components/Pages/MainPage.tsx
  FE/client/src/Components/SearchBar/Charge.tsx
  FE/client/src/Components/SearchBar/EntryDate.tsx
  FE/client/src/Components/SearchBar/Personnel.tsx
  FE/client/src/Components/SearchBar/index.tsx
  FE/client/src/Components/commons/base.tsx
  FE/client/src/Components/commons/searchBarType.tsx
  FE/client/src/Images/airbnbMain.jpg
  FE/client/src/index.tsx
  FE/client/src/react-app-env.d.ts
  FE/client/src/recoil/atoms.tsx
  FE/client/src/utils/calendarUtil.tsx
  FE/client/tsconfig.json
  FE/client/yarn.lock
  README.md
  iOS/.gitignore
Labels: review-fe

#3 [ 1팀 ] 시온 - 서버 배포 및 OAuth 리뷰 요청
  BE/README.md
  BE/airbnb/.gitignore
  BE/airbnb/build.gradle
  BE/airbnb/gradle/wrapper/gradle-wrapper.jar
  BE/airbnb/gradle/wrapper/gradle-wrapper.properties
  BE/airbnb/gradlew
  BE/airbnb/gradlew.bat
  BE/airbnb/settings.gradle
  BE/airbnb/src/main/java/team01/airbnb/AirbnbApplication.java
  BE/airbnb/src/main/java/team01/airbnb/config/WebConfig.java
  BE/airbnb/src/main/java/team01/airbnb/config/auth/LoginUser.java
  BE/airbnb/src/main/java/team01/airbnb/config/auth/LoginUserArgumentResolver.java
  BE/airbnb/src/main/java/team01/airbnb/config/auth/dto/SessionUser.java
  BE/airbnb/src/main/java/team01/airbnb/config/interceptor/LoginInterceptor.java
  BE/airbnb/src/main/java/team01/airbnb/config/interceptor/LogoutInterceptor.java
  BE/airbnb/src/main/java/team01/airbnb/controller/HomeController.java
  BE/airbnb/src/main/java/team01/airbnb/controller/UserController.java
  BE/airbnb/src/main/java/team01/airbnb/domain/User.java
  BE/airbnb/src/main/java/team01/airbnb/dto/ApiResult.java
  BE/airbnb/src/main/java/team01/airbnb/dto/KakaoLogout.java
  BE/airbnb/src/main/java/team01/airbnb/dto/KakaoProfile.java
  BE/airbnb/src/main/java/team01/airbnb/dto/OAuthToken.java
  BE/airbnb/src/main/java/team01/airbnb/dto/RoleType.java
  BE/airbnb/src/main/java/team01/airbnb/dto/SocialProfile.java
  BE/airbnb/src/main/java/team01/airbnb/exception/NoResultSetException.java
  BE/airbnb/src/main/java/team01/airbnb/exception/NotProcessJsonException.java
  BE/airbnb/src/main/java/team01/airbnb/exceptionHandler/GlobalExceptionHandler.java
  BE/airbnb/src/main/java/team01/airbnb/service/UserService.java
  BE/airbnb/src/main/java/team01/airbnb/utils/KakaoLoginUtils.java
  BE/airbnb/src/main/resources/application.properties
  BE/airbnb/src/main/resources/data.sql
  BE/airbnb/src/main/resources/schema.sql
  BE/airbnb/src/main/resources/static/image/kakao_login_button.png
  BE/airbnb/src/main/resources/templates/index.html
  BE/airbnb/src/main/resources/templates/layout/footer.html
  BE/airbnb/src/main/resources/templates/layout/header.html
  BE/airbnb/src/test/java/team01/airbnb/AirbnbApplicationTests.java
  BE/airbnb/src/test/java/team01/airbnb/service/UserServiceTest.java
  FE/README.md
  README.md
  iOS/README.md
Labels: review-be

#10 [TEAM-05 / FE] 메인화면 정적 UI 및 모달 토글
  README.md
  backend/README.md
  frontend/.gitignore
  frontend/.vscode/settings.json
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/hero.jpg
  frontend/public/index.html
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.tsx
  frontend/src/components/main/Main.tsx
  frontend/src/components/main/header/Header.tsx
  frontend/src/components/main/header/Logo.tsx
  frontend/src/components/main/header/Tour.tsx
  frontend/src/components/main/header/side_menu/SideContainer.tsx
  frontend/src/components/main/header/side_menu/UserMenu.tsx
  frontend/src/components/modals/calendar/CalendarModal.tsx
  frontend/src/components/modals/fee/FeeModal.tsx
  frontend/src/components/modals/guest/GuestModal.tsx
  frontend/src/components/modals/location/LocationModal.tsx
  frontend/src/components/search_bar/SearchBar.tsx
  frontend/src/components/search_bar/SearchFilter.tsx
  frontend/src/icons/check.svg
  frontend/src/icons/chevron-left.svg
  frontend/src/icons/chevron-right.svg
  frontend/src/icons/heart.svg
  frontend/src/icons/logo.svg
  frontend/src/icons/menu.svg
  frontend/src/icons/minus-circle.svg
  frontend/src/icons/minus.svg
  frontend/src/icons/pause-circle.svg
  frontend/src/icons/plus-circle.svg
  frontend/src/icons/plus.svg
  frontend/src/icons/search.svg
  frontend/src/icons/star.svg
  frontend/src/icons/user.svg
  frontend/src/icons/x-circle-hover.svg
  frontend/src/icons/x-circle.svg
  frontend/src/index.tsx
  frontend/src/react-app-env.d.ts
  frontend/src/styles/GlobalStyle.ts
  frontend/src/styles/ModalContainer.ts
  frontend/src/utils/interfaces.ts
  frontend/src/utils/parseByType.ts
  frontend/tsconfig.json
  ios/README.md
Labels: review-fe

#6 [team-07/FE] UI 뼈대 구성, tsx, context & reducer 상태관리
  fe/.eslintignore
  fe/.eslintrc
  fe/.gitignore
  fe/.prettierrc.js
  fe/README.md
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/src/App.css
  fe/src/App.tsx
  fe/src/Contexts.tsx
  fe/src/Router.tsx
  fe/src/components/accomodation/Accomodation.tsx
  fe/src/components/home/Covid19Message.tsx
  fe/src/components/home/Home.tsx
  fe/src/components/home/Main.tsx
  fe/src/components/home/mainComponents/BeingHost.tsx
  fe/src/components/home/mainComponents/Hero.tsx
  fe/src/components/home/mainComponents/HouseType.tsx
  fe/src/components/home/mainComponents/NearbyLocation.tsx
  fe/src/components/home/mainComponents/heroComponents/Header.tsx
  fe/src/components/home/mainComponents/heroComponents/Searcher.tsx
  fe/src/components/home/mainComponents/heroComponents/headerComponents/Account.tsx
  fe/src/components/home/mainComponents/heroComponents/searcherComponents/Calendar.tsx
  fe/src/components/home/mainComponents/heroComponents/searcherComponents/LocationTab.tsx
  fe/src/data/location.js
  fe/src/hooks/ReservationHook.tsx
  fe/src/hooks/SearcherHook.tsx
  fe/src/index.css
  fe/src/index.tsx
  fe/src/react-app-env.d.ts
  fe/src/shared/interface.ts
  fe/src/shared/reservationReducer.ts
  fe/src/shared/searchBarReducer.ts
  fe/text.bat
  fe/tsconfig.json
  fe/yarn.lock
  package-lock.json
Labels: review-fe

#15 [BE / Team-22] OAuth 로그인을 간단하게 구현
  .gitignore
  README.md
  backend/README.md
  backend/deploy-local.sh
  backend/docker/Dockerfile
  backend/docker/README.md
  backend/docker/db/conf/utf8.cnf
  backend/docker/db/initdb/schema.sql
  backend/docker/docker-clear.sh
  backend/docker/docker-start.sh
  backend/server/.gitignore
  backend/server/build.gradle
  backend/server/gradle/wrapper/gradle-wrapper.jar
  backend/server/gradle/wrapper/gradle-wrapper.properties
  backend/server/gradlew
  backend/server/gradlew.bat
  backend/server/run.sh
  backend/server/settings.gradle
  backend/server/src/main/java/com/airbnb/AirbnbApplication.java
  backend/server/src/main/java/com/airbnb/annotation/LoginRequired.java
  backend/server/src/main/java/com/airbnb/config/InterceptorConfig.java
  backend/server/src/main/java/com/airbnb/controller/AuthController.java
  backend/server/src/main/java/com/airbnb/controller/ExceptionController.java
  backend/server/src/main/java/com/airbnb/dao/TokenDao.java
  backend/server/src/main/java/com/airbnb/dao/UserDao.java
  backend/server/src/main/java/com/airbnb/dao/datasource/DataSource.java
  backend/server/src/main/java/com/airbnb/dao/datasource/PersistentDataSource.java
  backend/server/src/main/java/com/airbnb/dao/datasource/SessionDataSource.java
  backend/server/src/main/java/com/airbnb/domain/Token.java
  backend/server/src/main/java/com/airbnb/domain/User.java
  backend/server/src/main/java/com/airbnb/dto/AccessTokenRequest.java
  backend/server/src/main/java/com/airbnb/dto/AccessTokenResponse.java
  backend/server/src/main/java/com/airbnb/dto/AuthRequest.java
  backend/server/src/main/java/com/airbnb/dto/AuthResponse.java
  backend/server/src/main/java/com/airbnb/dto/MessageResponse.java
  backend/server/src/main/java/com/airbnb/dto/UserDto.java
  backend/server/src/main/java/com/airbnb/exception/AuthenticationException.java
  backend/server/src/main/java/com/airbnb/exception/DataSourceException.java
  backend/server/src/main/java/com/airbnb/exception/GitHubException.java
  backend/server/src/main/java/com/airbnb/exception/JwtException.java
  backend/server/src/main/java/com/airbnb/exception/SqlException.java
  backend/server/src/main/java/com/airbnb/intercepter/LoginInterceptor.java
  backend/server/src/main/java/com/airbnb/service/AuthService.java
  backend/server/src/main/java/com/airbnb/service/GitHubService.java
  backend/server/src/main/java/com/airbnb/service/UserService.java
  backend/server/src/main/java/com/airbnb/util/JwtUtil.java
  backend/server/src/main/resources/application.properties
  backend/server/src/main/resources/schema.sql
  backend/server/src/main/resources/static/callback.html
  backend/server/src/main/resources/static/home.html
  backend/server/src/main/resources/static/index.html
  backend/server/src/test/java/com/airbnb/AirbnbApplicationTests.java
  backend/start.sh
  frontend/README.md
Labels: review-be

#9 [ team-11 / FE ] SearchBar & Oauth
  FE/src/App.js
  FE/src/components/Footer/AnyWhere.jsx
  FE/src/components/Footer/Floor.jsx
  FE/src/components/Footer/Footer.jsx
  FE/src/components/Footer/NearTravel.jsx
  FE/src/components/Header/Header.jsx
  FE/src/components/Header/Logo.jsx
  FE/src/components/Header/Menu.jsx
  FE/src/components/Header/MyPage.jsx
  FE/src/components/Header/SearchBar/CloseButton.jsx
  FE/src/components/Header/SearchBar/Period/Calendar/Calendar.jsx
  FE/src/components/Header/SearchBar/Period/Calendar/Day.jsx
  FE/src/components/Header/SearchBar/Period/CalendarModal.jsx
  FE/src/components/Header/SearchBar/Period/Period.jsx
  FE/src/components/Header/SearchBar/Personnel/Personnel.jsx
  FE/src/components/Header/SearchBar/Personnel/PersonnelModal.jsx
  FE/src/components/Header/SearchBar/Price/Price.jsx
  FE/src/components/Header/SearchBar/Price/PriceModal.jsx
  FE/src/components/Header/SearchBar/Price/Slider.jsx
  FE/src/components/Header/SearchBar/SearchBar.jsx
  FE/src/components/Header/SearchBar/SearchButton.jsx
  FE/src/components/Main/AnyWhere.jsx
  FE/src/components/Main/Main.jsx
  FE/src/components/Main/NearTravel.jsx
  FE/src/components/Result/Result.jsx
  FE/src/components/Root.jsx
  FE/src/components/SearchBar/Price/Price.jsx
  FE/src/components/SearchBar/SearchBar.jsx
  FE/src/config/GlobalStyle.jsx
  FE/src/config/MainContextProvider.jsx
  FE/src/config/SearchBarContextProvider.jsx
  FE/src/json/data.json
  FE/src/util/addComma.js
  FE/src/util/delay.js
Labels: review-fe

#13 [Team-09 Eamon] 메인 UI 와 modal component 작성
  .gitignore
  README.md
  fe/.env
  fe/.gitignore
  fe/README.md
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/public/main.jpg
  fe/src/App.tsx
  fe/src/components/common/Modal.tsx
  fe/src/components/main/Main.tsx
  fe/src/components/main/header/AccountMenu.tsx
  fe/src/components/main/header/Header.tsx
  fe/src/components/main/header/LogInList.tsx
  fe/src/components/main/header/Logo.tsx
  fe/src/components/main/header/MenuItem.tsx
  fe/src/components/main/header/Menus.tsx
  fe/src/components/main/searchbar/InputItem.tsx
  fe/src/components/main/searchbar/SearchBarBtn.tsx
  fe/src/components/main/searchbar/Searchbar.tsx
  fe/src/components/main/searchbar/date-input/DateInput.tsx
  fe/src/components/main/searchbar/people-input/PeopleInput.tsx
  fe/src/components/main/searchbar/people-input/PeopleItem.tsx
  fe/src/components/main/searchbar/people-input/PeopleList.tsx
  fe/src/components/main/searchbar/price-input/PriceInput.tsx
  fe/src/hooks/useOnClickOutside.tsx
  fe/src/index.css
  fe/src/index.tsx
  fe/src/pages/Home.tsx
  fe/src/pages/LogIn.tsx
  fe/src/react-app-env.d.ts
  fe/src/style/GlobalStyle.tsx
  fe/src/style/theme.ts
  fe/tsconfig.json
Labels: review-fe

#14 [Team-13 / FE] PR 1회차
  .gitignore
  be/README.md
  fe/airbnb-fe/.gitignore
  fe/airbnb-fe/README.md
  fe/airbnb-fe/package.json
  fe/airbnb-fe/public/index.html
  fe/airbnb-fe/src/App.css
  fe/airbnb-fe/src/App.tsx
  fe/airbnb-fe/src/components/Header/Header.tsx
  fe/airbnb-fe/src/components/ReservationBar/CalendarSlider/Calendar.tsx
  fe/airbnb-fe/src/components/ReservationBar/CalendarSlider/CalendarSlider.tsx
  fe/airbnb-fe/src/components/ReservationBar/CalendarSlider/atoms.tsx
  fe/airbnb-fe/src/components/ReservationBar/LocationSearch/LocationSearch.tsx
  fe/airbnb-fe/src/components/ReservationBar/ReservationBar.tsx
  fe/airbnb-fe/src/components/ReservationBar/ReservationBarBtn.tsx
  fe/airbnb-fe/src/components/ReservationBar/ReservationBarDropPopup.tsx
  fe/airbnb-fe/src/components/ReservationBar/atoms.tsx
  fe/airbnb-fe/src/index.css
  fe/airbnb-fe/src/index.tsx
  fe/airbnb-fe/src/pages/MainPage.tsx
  fe/airbnb-fe/src/react-app-env.d.ts
  fe/airbnb-fe/src/reportWebVitals.ts
  fe/airbnb-fe/src/util/API.ts
  fe/airbnb-fe/tsconfig.json
  ios/README.md
Labels: review-fe

#23 [Team 1][FE] 메인 UI 헤더, 캘린더
  FE/airbnb/.gitignore
  FE/airbnb/README.md
  FE/airbnb/package-lock.json
  FE/airbnb/package.json
  FE/airbnb/public/index.html
  FE/airbnb/public/manifest.json
  FE/airbnb/public/robots.txt
  FE/airbnb/src/App.css
  FE/airbnb/src/App.tsx
  FE/airbnb/src/assets/svg/Property 1=check.svg
  FE/airbnb/src/assets/svg/Property 1=chevron-left.svg
  FE/airbnb/src/assets/svg/Property 1=chevron-right.svg
  FE/airbnb/src/assets/svg/Property 1=heart.svg
  FE/airbnb/src/assets/svg/Property 1=menu.svg
  FE/airbnb/src/assets/svg/Property 1=minus-circle.svg
  FE/airbnb/src/assets/svg/Property 1=pause-circle.svg
  FE/airbnb/src/assets/svg/Property 1=plus-circle.svg
  FE/airbnb/src/assets/svg/Property 1=search.svg
  FE/airbnb/src/assets/svg/Property 1=star.svg
  FE/airbnb/src/assets/svg/Property 1=user.svg
  FE/airbnb/src/assets/svg/Property 1=x-circle.svg
  FE/airbnb/src/assets/svg/minus.svg
  FE/airbnb/src/assets/svg/plus.svg
  FE/airbnb/src/components/calendar/Calendar.tsx
  FE/airbnb/src/components/calendar/CalendarDate.tsx
  FE/airbnb/src/components/calendar/CalendarHeader.tsx
  FE/airbnb/src/components/header/Header.tsx
  FE/airbnb/src/components/header/HoverBlock.tsx
  FE/airbnb/src/components/header/form/FormCalendar.tsx
  FE/airbnb/src/components/header/form/FormCheckIn.tsx
  FE/airbnb/src/components/header/form/FormCheckOut.tsx
  FE/airbnb/src/components/header/form/FormColumn.tsx
  FE/airbnb/src/components/header/form/FormGuest.tsx
  FE/airbnb/src/components/header/form/FormGuestToggle.tsx
  FE/airbnb/src/components/header/form/FormLocation.tsx
  FE/airbnb/src/components/header/form/FormLocationToggle.tsx
  FE/airbnb/src/components/header/form/FormPrice.tsx
  FE/airbnb/src/components/header/form/FormPriceToggle.tsx
  FE/airbnb/src/components/header/form/HeaderForm.tsx
  FE/airbnb/src/components/header/nav/HeaderNav.tsx
  FE/airbnb/src/components/header/nav/NavUserToggle.tsx
  FE/airbnb/src/components/header/tab/HeaderTab.tsx
  FE/airbnb/src/components/header/tab/HeaderTabList.tsx
  FE/airbnb/src/components/util/utilStyles.ts
  FE/airbnb/src/hooks/useToggle.ts
  FE/airbnb/src/index.css
  FE/airbnb/src/index.tsx
  FE/airbnb/src/pages/MainPage.tsx
  FE/airbnb/src/react-app-env.d.ts
  FE/airbnb/src/recoil/headerAtom.ts
  FE/airbnb/src/theme.ts
  FE/airbnb/tsconfig.json
  FE/airbnb/yarn.lock
  README.md
Labels: review-fe

#17 [Team-05 / BE] API 기본기능 구현
  .gitignore
  backend/.gitignore
  backend/HELP.md
  backend/build.gradle
  backend/docker/.gitignore
  backend/docker/README.md
  backend/docker/db/conf/custom.cnf
  backend/docker/db/initdb/1-init.sql
  backend/docker/docker-clear.sh
  backend/docker/docker-compose.yml
  backend/docker/docker-start.sh
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/com/example/airbnb/AirbnbApplication.java
  backend/src/main/java/com/example/airbnb/config/SwaggerConfig.java
  backend/src/main/java/com/example/airbnb/config/WebConfig.java
  backend/src/main/java/com/example/airbnb/controller/CityController.java
  backend/src/main/java/com/example/airbnb/controller/ReservationController.java
  backend/src/main/java/com/example/airbnb/controller/RoomController.java
  backend/src/main/java/com/example/airbnb/dao/CityDAO.java
  backend/src/main/java/com/example/airbnb/dao/ImageDAO.java
  backend/src/main/java/com/example/airbnb/dao/LocationDAO.java
  backend/src/main/java/com/example/airbnb/dao/ReservationDAO.java
  backend/src/main/java/com/example/airbnb/dao/RoomDAO.java
  backend/src/main/java/com/example/airbnb/domain/City.java
  backend/src/main/java/com/example/airbnb/domain/Image.java
  backend/src/main/java/com/example/airbnb/domain/Location.java
  backend/src/main/java/com/example/airbnb/domain/Reservation.java
  backend/src/main/java/com/example/airbnb/domain/Room.java
  backend/src/main/java/com/example/airbnb/domain/User.java
  backend/src/main/java/com/example/airbnb/dto/CityDTO.java
  backend/src/main/java/com/example/airbnb/dto/ImageDTO.java
  backend/src/main/java/com/example/airbnb/dto/LocationDTO.java
  backend/src/main/java/com/example/airbnb/dto/MainPageDTO.java
  backend/src/main/java/com/example/airbnb/dto/PriceDTO.java
  backend/src/main/java/com/example/airbnb/dto/Receipt.java
  backend/src/main/java/com/example/airbnb/dto/ReservationDTO.java
  backend/src/main/java/com/example/airbnb/dto/RoomDTO.java
  backend/src/main/java/com/example/airbnb/dto/RoomDetailDTO.java
  backend/src/main/java/com/example/airbnb/dto/RoomListDTO.java
  backend/src/main/java/com/example/airbnb/exception/ConditionException.java
  backend/src/main/java/com/example/airbnb/exception/NotFoundDataException.java
  backend/src/main/java/com/example/airbnb/service/CityService.java
  backend/src/main/java/com/example/airbnb/service/ReservationService.java
  backend/src/main/java/com/example/airbnb/service/RoomService.java
  backend/src/main/java/com/example/airbnb/utils/Calculators.java
  backend/src/main/java/com/example/airbnb/utils/SQL.kt
  backend/src/main/resources/application.properties
  backend/src/main/resources/data.sql
  backend/src/main/resources/schema.sql
  backend/src/test/java/com/example/airbnb/AirbnbApplicationTests.java
  frontend/README.md
Labels: review-be

#24 [Team07 / FE] 캘린더 구현
  fe/src/App.tsx
  fe/src/components/home/Home.tsx
  fe/src/components/home/MainContents.tsx
  fe/src/components/home/mainComponents/heroComponents/Searcher.tsx
  fe/src/components/home/mainComponents/heroComponents/searcherComponents/Calendar.tsx
  fe/src/components/home/mainComponents/heroComponents/searcherComponents/CheckInTab.tsx
  fe/src/components/home/mainComponents/heroComponents/searcherComponents/CheckOutTab.tsx
  fe/src/components/home/mainComponents/heroComponents/searcherComponents/FeeTab.tsx
  fe/src/components/home/mainComponents/heroComponents/searcherComponents/LocationTab.tsx
  fe/src/components/home/mainComponents/heroComponents/searcherComponents/PeopleTab.tsx
  fe/src/components/home/mainComponents/heroComponents/searcherComponents/calendar/Calendar.tsx
  fe/src/components/home/mainComponents/heroComponents/searcherComponents/calendar/calendarChecker.ts
  fe/src/components/home/mainComponents/heroComponents/searcherComponents/calendar/calendarDate.ts
  fe/src/components/home/mainComponents/heroComponents/searcherComponents/shared.style.tsx
  fe/src/shared/interface.ts
  fe/src/shared/searchBarReducer.ts
  fe/src/styles/styled.d.ts
  fe/src/styles/theme.ts
Labels: review-fe

#7 [team-4 롤로] 장소 검색 화면 & 네트워크 모델(+ Fake Data)
  .commit_template
  .gitignore
  BE/init
  FE/init
  IOS/airbnb/airbnb.xcodeproj/project.pbxproj
  IOS/airbnb/airbnb.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  IOS/airbnb/airbnb.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  IOS/airbnb/airbnb.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  IOS/airbnb/airbnb.xcodeproj/xcshareddata/xcschemes/airbnb.xcscheme
  IOS/airbnb/airbnb/AccomodationConditions/AccomodationConditions.storyboard
  IOS/airbnb/airbnb/AccomodationConditions/CalendarSelect/CalendarViewController.swift
  IOS/airbnb/airbnb/AccomodationConditions/LocationSearch/Entity/LocationSearchResult.swift
  IOS/airbnb/airbnb/AccomodationConditions/LocationSearch/Entity/PopularLocation.swift
  IOS/airbnb/airbnb/AccomodationConditions/LocationSearch/View/PopularLocationTableViewCell.swift
  IOS/airbnb/airbnb/AccomodationConditions/LocationSearch/View/SearchResultTableViewCell.swift
  IOS/airbnb/airbnb/AccomodationConditions/LocationSearch/ViewController/LocationSearchController.swift
  IOS/airbnb/airbnb/AccomodationConditions/LocationSearch/ViewController/LocationSearchResultUpdating.swift
  IOS/airbnb/airbnb/AccomodationConditions/LocationSearch/ViewController/PopularLocationTableViewDataSource.swift
  IOS/airbnb/airbnb/AccomodationConditions/LocationSearch/ViewController/PopularLocationViewController.swift
  IOS/airbnb/airbnb/AccomodationConditions/LocationSearch/ViewController/SearchResultTableViewController.swift
  IOS/airbnb/airbnb/AccomodationConditions/LocationSearch/ViewController/SearchResultTableViewDataSource.swift
  IOS/airbnb/airbnb/AccomodationConditions/LocationSearch/ViewModel/PopularLocationLoadModel.swift
  IOS/airbnb/airbnb/AccomodationConditions/LocationSearch/ViewModel/PopularLocationViewModel.swift
  IOS/airbnb/airbnb/AccomodationConditions/LocationSearch/ViewModel/SearchResultUpdateModel.swift
  IOS/airbnb/airbnb/AccomodationConditions/LocationSearch/ViewModel/SearchResultViewModel.swift
  IOS/airbnb/airbnb/AppCycle/AppDelegate.swift
  IOS/airbnb/airbnb/AppCycle/SceneDelegate.swift
  IOS/airbnb/airbnb/Assets.xcassets/AccentColor.colorset/Contents.json
  IOS/airbnb/airbnb/Assets.xcassets/AppIcon.appiconset/Contents.json
  IOS/airbnb/airbnb/Assets.xcassets/Contents.json
  IOS/airbnb/airbnb/Base.lproj/LaunchScreen.storyboard
  IOS/airbnb/airbnb/Info.plist
  IOS/airbnb/airbnb/Main/Base.lproj/Main.storyboard
  IOS/airbnb/airbnb/Main/UseCase/HeroImageUseCase.swift
  IOS/airbnb/airbnb/Main/UseCase/ImageLoadUseCase.swift
  IOS/airbnb/airbnb/Main/ViewController/HomeViewController.swift
  IOS/airbnb/airbnb/Main/ViewModel/HomeViewModel.swift
  IOS/airbnb/airbnb/Main/ViewModel/ImagePathLoadModel.swift
  IOS/airbnb/airbnb/Network/AlamofireImageLoadManager.swift
  IOS/airbnb/airbnb/Network/AlamofireNetworkManager.swift
  IOS/airbnb/airbnb/Network/AlamofireRequestManagable.swift
  IOS/airbnb/airbnb/Network/AlamofireRequestManager.swift
  IOS/airbnb/airbnb/Network/Fake/FakeNetworkManager.swift
  IOS/airbnb/airbnb/Network/ImageLoadManagable.swift
  IOS/airbnb/airbnb/Network/NetworkError.swift
  IOS/airbnb/airbnb/Network/NetworkManagable.swift
  IOS/init
  README.md
  iOS/airbnb/NetworkServiceTest/FakeData.swift
  iOS/airbnb/NetworkServiceTest/Info.plist
  iOS/airbnb/NetworkServiceTest/NetworkServiceTest.swift
  iOS/airbnb/NetworkServiceTest/NetworkTestMockClasses.swift
  iOS/airbnb/airbnb/AccomodationConditions/LocationSearch/UseCase/PopularLocationLoadUseCase.swift
  iOS/airbnb/airbnb/AccomodationConditions/LocationSearch/UseCase/PopularLocationUseCase.swift
  iOS/airbnb/airbnb/AccomodationConditions/LocationSearch/UseCase/SearchResultFetchUseCase.swift
  iOS/airbnb/airbnb/AccomodationConditions/LocationSearch/UseCase/SearchResultUseCase.swift
  iOS/airbnb/airbnb/Factory/AlertFactory.swift
  iOS/airbnb/airbnb/Factory/SearchBarFactory.swift
  iOS/airbnb/airbnb/Factory/StoryboardFactory.swift
  iOS/airbnb/airbnb/Factory/ViewControllerFactory.swift
Labels: review-iOS

#32 [team-13, FE] PR 2회차
  fe/airbnb-fe/src/components/ReservationBar/PricePlotSlider/CurvedPlot.tsx
  fe/airbnb-fe/src/components/ReservationBar/PricePlotSlider/PricePlotSlider.tsx
  fe/airbnb-fe/src/components/ReservationBar/PricePlotSlider/SliderBtn.tsx
  fe/airbnb-fe/src/components/ReservationBar/PricePlotSlider/type.tsx
  fe/airbnb-fe/src/components/ReservationBar/ReservationBar.tsx
  fe/airbnb-fe/src/components/ReservationBar/ReservationBarBtn.tsx
  fe/airbnb-fe/src/components/ReservationBar/ReservationBarDropPopup.tsx
  fe/airbnb-fe/src/components/ReservationBar/atoms.tsx
  fe/airbnb-fe/src/rsc/slider-btn.svg
  fe/airbnb-fe/src/util/hooks/useFetch.tsx
Labels: review-fe

#22 [Team18 - Min, ZG (iOS)] 메인화면, 검색화면, 조건설정화면 구현
  BE/README.md
  iOS/.gitignore
  iOS/README.md
  iOS/airbnb/airbnb.xcodeproj/project.pbxproj
  iOS/airbnb/airbnb.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/airbnb/airbnb.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/airbnb/airbnb.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  iOS/airbnb/airbnb/Assets.xcassets/AccentColor.colorset/Contents.json
  iOS/airbnb/airbnb/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/airbnb/airbnb/Assets.xcassets/Contents.json
  iOS/airbnb/airbnb/Assets.xcassets/mainView.imageset/27e59a819a2b8cb93633590403acaa63.jpeg
  iOS/airbnb/airbnb/Assets.xcassets/mainView.imageset/Contents.json
  iOS/airbnb/airbnb/Base.lproj/LaunchScreen.storyboard
  iOS/airbnb/airbnb/Base.lproj/Main.storyboard
  iOS/airbnb/airbnb/Controller/ConditionViewTableViewDataSource.swift
  iOS/airbnb/airbnb/Controller/FindingAccommdationViewController.swift
  iOS/airbnb/airbnb/Controller/RecommendTripCollectionViewDataSource.swift
  iOS/airbnb/airbnb/Controller/SearchViewController.swift
  iOS/airbnb/airbnb/Controller/SuggestionsTableViewController.swift
  iOS/airbnb/airbnb/Controller/TripPlaceCollectionViewDataSource.swift
  iOS/airbnb/airbnb/Controller/ViewController.swift
  iOS/airbnb/airbnb/Info.plist
  iOS/airbnb/airbnb/LifeCycle/AppDelegate.swift
  iOS/airbnb/airbnb/LifeCycle/SceneDelegate.swift
  iOS/airbnb/airbnb/Model/Data/ConditionPageData/FindingAccommdationCondition.swift
  iOS/airbnb/airbnb/Model/Data/FirstPageData/RecommendTrip.swift
  iOS/airbnb/airbnb/Model/Data/FirstPageData/SearchCondition.swift
  iOS/airbnb/airbnb/Model/Data/FirstPageData/TripPlace.swift
  iOS/airbnb/airbnb/Model/Data/FirstPageData/WishList.swift
  iOS/airbnb/airbnb/Model/Data/SearchResultData/RoomData.swift
  iOS/airbnb/airbnb/Model/Data/SearchResultData/SearchResultData.swift
  iOS/airbnb/airbnb/Model/Network/EndPoint.swift
  iOS/airbnb/airbnb/Model/Network/MainPageDTO.swift
  iOS/airbnb/airbnb/Model/Network/Network.swift
  iOS/airbnb/airbnb/View/CalendarView.swift
  iOS/airbnb/airbnb/View/ConditionViewTableViewCell.swift
  iOS/airbnb/airbnb/View/CondtionsTableViewCell.swift
  iOS/airbnb/airbnbTests/Info.plist
  iOS/airbnb/airbnbTests/airbnbTests.swift
  iOS/airbnb/airbnbUITests/Info.plist
  iOS/airbnb/airbnbUITests/airbnbUITests.swift
Labels: review-iOS

#25 [ team12 ] 더미데이터 기반 UI, TypeScript로 Calendar library 제작
  .gitignore
  README.md
  README.old.md
  package-lock.json
  package.json
  public/favicon.ico
  public/hero.png
  public/img_location.webp
  public/index.html
  public/robots.txt
  src/App.js
  src/App.test.js
  src/assets/svg/img_hamberger.svg
  src/assets/svg/img_language.svg
  src/assets/svg/img_logo.svg
  src/assets/svg/img_myPage.svg
  src/assets/svg/img_search.svg
  src/components/header/Header.js
  src/components/header/MyPage.js
  src/components/header/menu/Menu.js
  src/components/header/menu/SearchForm.js
  src/components/header/menu/SearchInput.js
  src/components/header/menu/input/CalendarBox.tsx
  src/components/header/menu/input/Chart.js
  src/components/header/menu/input/Guest.js
  src/components/home/Footer.js
  src/components/home/HomePage.js
  src/components/home/Location.js
  src/components/home/Thema.js
  src/components/search/SearchPage.js
  src/components/search/SearchResult.js
  src/index.css
  src/index.js
  src/lib/Calendar.tsx
  src/lib/CalendarItem.tsx
  src/lib/CalendarProvider.tsx
  src/lib/Carousel.tsx
  src/lib/Test.tsx
  src/lib/constant.ts
  src/lib/type.tsx
  src/react-app-env.d.ts
  src/reportWebVitals.js
  src/setupTests.js
  src/utils/GlobalStyles.js
  src/utils/constant.js
  src/utils/dummy.js
  tsconfig.json
  yarn.lock
Labels: review-fe

#36 [ team-03 / FE ] 메인페이지 ui, 구글맵 API 연동
  FE/client/.gitignore
  FE/client/package.json
  FE/client/src/App.tsx
  FE/client/src/Components/GNB/SearchMapNav.tsx
  FE/client/src/Components/GNB/index.tsx
  FE/client/src/Components/HotelList/HotelItem.tsx
  FE/client/src/Components/HotelList/HotelListHeader.tsx
  FE/client/src/Components/HotelList/index.tsx
  FE/client/src/Components/Modal/ChargeModal.tsx
  FE/client/src/Components/Modal/Graph.tsx
  FE/client/src/Components/Modal/PersonnelKind.tsx
  FE/client/src/Components/Modal/PersonnelModal.tsx
  FE/client/src/Components/Modal/Slider.tsx
  FE/client/src/Components/Modal/index.tsx
  FE/client/src/Components/Pages/MainPage.tsx
  FE/client/src/Components/Pages/SearchMapPage.tsx
  FE/client/src/Components/SearchBar/Charge.tsx
  FE/client/src/Components/SearchBar/DateKind.tsx
  FE/client/src/Components/SearchBar/EntryDate.tsx
  FE/client/src/Components/SearchBar/Personnel.tsx
  FE/client/src/Components/SearchBar/index.tsx
  FE/client/src/Components/SearchMap/index.tsx
  FE/client/src/Components/commons/base.jsx
  FE/client/src/index.tsx
  FE/client/src/react-app-env.d.ts
  FE/client/src/recoil/atoms.tsx
  FE/client/src/utils/graphData.js
  FE/client/src/utils/graphUtil.tsx
  FE/client/yarn.lock
Labels: review-fe

#37 [TEAM-06 / FE / Q ] 메인 페이지 UI 및 캘린더 캐러셀
  fe/.gitignore
  fe/README.md
  fe/config-overrides.js
  fe/package-lock.json
  fe/package.json
  fe/public/airbnb-logo.png
  fe/public/hero-img.png
  fe/public/index.html
  fe/src/App.tsx
  fe/src/assets/check.svg
  fe/src/assets/chevron-left.svg
  fe/src/assets/chevron-right.svg
  fe/src/assets/heart.svg
  fe/src/assets/menu.svg
  fe/src/assets/minus-circle.svg
  fe/src/assets/minus.svg
  fe/src/assets/pause-circle.svg
  fe/src/assets/plus-circle.svg
  fe/src/assets/plus.svg
  fe/src/assets/search.svg
  fe/src/assets/star.svg
  fe/src/assets/user.svg
  fe/src/assets/x-circle.svg
  fe/src/components/Header/Calender/Calendar.tsx
  fe/src/components/Header/Calender/CalendarWrap.tsx
  fe/src/components/Header/Calender/Day.tsx
  fe/src/components/Header/Calender/DayOfTheWeek.tsx
  fe/src/components/Header/Nav/Form.tsx
  fe/src/components/Header/Nav/Logo.tsx
  fe/src/components/Header/Nav/Menu.tsx
  fe/src/components/Header/Nav/Nav.tsx
  fe/src/components/Header/PageHeader.tsx
  fe/src/components/Header/ProfileMenu/Login.tsx
  fe/src/components/Header/ProfileMenu/Profile.tsx
  fe/src/components/Header/Search/Count.tsx
  fe/src/components/Header/Search/Date.tsx
  fe/src/components/Header/Search/Fare.tsx
  fe/src/components/Header/Search/GuestItem.tsx
  fe/src/components/Header/Search/GuestModal.tsx
  fe/src/components/Header/Search/Guests.tsx
  fe/src/components/Header/Search/SearchBar.tsx
  fe/src/components/Header/Search/SearchButton.tsx
  fe/src/components/common/Title.tsx
  fe/src/components/common/childType.ts
  fe/src/components/common/smallText.tsx
  fe/src/index.tsx
  fe/src/pages/LandingPage.tsx
  fe/src/pages/SearchResult.tsx
  fe/src/react-app-env.d.ts
  fe/src/recoil/atoms/calendarState.ts
  fe/src/recoil/atoms/date.ts
  fe/src/recoil/atoms/guests.ts
  fe/src/recoil/atoms/profileModal.ts
  fe/src/styles/reset.css
  fe/src/styles/theme.js
  fe/tsconfig.json
  fe/tsconfig.path.json
  fe/yarn.lock
Labels: review-fe

#40 [Team-01 iOS] 메인 View부터 Price 설정 슬라이드 뷰까지의 흐름 UI 구현
  iOS/AirBed&Breakfast/AirBed&Breakfast.xcodeproj/project.pbxproj
  iOS/AirBed&Breakfast/AirBed&Breakfast.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/AirBed&Breakfast/AirBed&Breakfast.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/AirBed&Breakfast/AirBed&Breakfast.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  iOS/AirBed&Breakfast/AirBed&Breakfast.xcodeproj/xcuserdata/jojung-yun.xcuserdatad/xcschemes/xcschememanagement.plist
  iOS/AirBed&Breakfast/AirBed&Breakfast/Application/AppDelegate.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Application/DateExtension.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Application/SceneDelegate.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/Controllers/ReservationDetailViewController.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/Controllers/SearchViewController.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/Controllers/SetUpViewController.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/Controllers/WelcomeViewController.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/Base.lproj/Main.storyboard
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/CalendarView/CalendarControlView.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/CalendarView/DayLabel.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/CalendarView/DayRangeIndicatorView.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/PriceSlideView/PriceSlideControlView.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/PriceSlideView/RangeSlider.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/SearchResultCollectionView/SearchResultCollectionViewCell.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/SearchResultCollectionView/SearchResultCollectionViewCell.xib
  iOS/AirBed&Breakfast/AirBed&Breakfast/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  iOS/AirBed&Breakfast/AirBed&Breakfast/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/AirBed&Breakfast/AirBed&Breakfast/Resources/Assets.xcassets/Contents.json
  iOS/AirBed&Breakfast/AirBed&Breakfast/Resources/Base.lproj/LaunchScreen.storyboard
  iOS/AirBed&Breakfast/AirBed&Breakfast/Resources/Info.plist
  iOS/AirBed&Breakfast/AirBed&BreakfastTests/AirBed_BreakfastTests.swift
  iOS/AirBed&Breakfast/AirBed&BreakfastTests/Info.plist
  iOS/AirBed&Breakfast/README.md
  iOS/README.md
Labels: review-iOS

#43 [ team-11 / FE ] 완성
  FE/public/index.html
  FE/src/App.js
  FE/src/components/Footer/Footer.jsx
  FE/src/components/Header/Header.jsx
  FE/src/components/Header/MyPage.jsx
  FE/src/components/Header/SearchBar/Period/Calendar/Calendar.jsx
  FE/src/components/Header/SearchBar/Period/CalendarModal.jsx
  FE/src/components/Header/SearchBar/Period/Period.jsx
  FE/src/components/Header/SearchBar/Personnel/Personnel.jsx
  FE/src/components/Header/SearchBar/Price/Price.jsx
  FE/src/components/Header/SearchBar/Price/PriceModal.jsx
  FE/src/components/Header/SearchBar/SearchBar.jsx
  FE/src/components/Header/SearchBar/SearchButton.jsx
  FE/src/components/Result/Houses/House.jsx
  FE/src/components/Result/Houses/Houses.jsx
  FE/src/components/Result/Map.jsx
  FE/src/components/Result/Modal.jsx
  FE/src/components/Result/ModalCost.jsx
  FE/src/components/Result/ModalInfo.jsx
  FE/src/components/Result/Result.jsx
  FE/src/components/Root.jsx
  FE/src/config/MainContextProvider.jsx
  FE/src/config/ResultContextProvider.jsx
  FE/src/config/SearchBarContextProvider.jsx
  FE/src/util/parseDate.js
Labels: review-fe

#44 [TEAM15_FE] PR1
  frontend/.env
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/hamburger_btn.png
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/nextBtn.png
  frontend/public/prevBtn.png
  frontend/public/robots.txt
  frontend/public/user_img.png
  frontend/src/App.css
  frontend/src/App.test.tsx
  frontend/src/App.tsx
  frontend/src/Interface.tsx
  frontend/src/components/header/CenterMenu.tsx
  frontend/src/components/header/Header.tsx
  frontend/src/components/header/Logo.tsx
  frontend/src/components/header/UserInfo.tsx
  frontend/src/components/searchBar/SearchBar.tsx
  frontend/src/components/searchBar/date/Calendar.tsx
  frontend/src/components/searchBar/date/CheckIn.tsx
  frontend/src/components/searchBar/date/CheckOut.tsx
  frontend/src/components/searchBar/date/Date.tsx
  frontend/src/components/searchBar/date/ModalCalendar.tsx
  frontend/src/components/searchBar/fee/Fee.tsx
  frontend/src/components/searchBar/fee/ModalFee.tsx
  frontend/src/components/searchBar/personnel/ModalPersonnel.tsx
  frontend/src/components/searchBar/personnel/Personnel.tsx
  frontend/src/components/searchBar/place/ModalPlace.tsx
  frontend/src/components/searchBar/place/Place.tsx
  frontend/src/components/searchBar/searchBtn/SearchBtn.tsx
  frontend/src/customHook/atoms.tsx
  frontend/src/customHook/axiosAPI.tsx
  frontend/src/customHook/reducer.tsx
  frontend/src/customHook/useAxios.tsx
  frontend/src/customHook/useDateInfo.tsx
  frontend/src/customHook/useModalCtrlArray.tsx
  frontend/src/index.css
  frontend/src/index.tsx
  frontend/src/react-app-env.d.ts
  frontend/src/reportWebVitals.ts
  frontend/src/setupTests.ts
  frontend/src/style/BarStyle.tsx
  frontend/src/style/GlobalStyle.tsx
  frontend/src/style/Theme.tsx
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: review-fe

#16 [TEAM 2 / BE] 지역, 날짜, 가격, 인원 조건에 따른 숙소 검색 기능 구현
  .DS_Store
  BE/.DS_Store
  BE/.idea/workspace.xml
  BE/airbnb/.gitignore
  BE/airbnb/HELP.md
  BE/airbnb/build.gradle
  BE/airbnb/gradle/wrapper/gradle-wrapper.jar
  BE/airbnb/gradle/wrapper/gradle-wrapper.properties
  BE/airbnb/gradlew
  BE/airbnb/gradlew.bat
  BE/airbnb/settings.gradle
  BE/airbnb/src/main/java/mj/airbnb/AirbnbApplication.java
  BE/airbnb/src/main/java/mj/airbnb/domain/accommodation/Accommodation.java
  BE/airbnb/src/main/java/mj/airbnb/domain/accommodation/AccommodationRepository.java
  BE/airbnb/src/main/java/mj/airbnb/domain/reservation/Reservation.java
  BE/airbnb/src/main/java/mj/airbnb/domain/reservation/ReservationRepository.java
  BE/airbnb/src/main/java/mj/airbnb/service/AccommodationService.java
  BE/airbnb/src/main/java/mj/airbnb/service/ReservationService.java
  BE/airbnb/src/main/java/mj/airbnb/web/AccommodationController.java
  BE/airbnb/src/main/java/mj/airbnb/web/DestinationController.java
  BE/airbnb/src/main/java/mj/airbnb/web/ReservationController.java
  BE/airbnb/src/main/java/mj/airbnb/web/dto/AccommodationResponseDto.java
  BE/airbnb/src/main/java/mj/airbnb/web/dto/SearchRequestDto.java
  BE/airbnb/src/main/resources/application.properties
  BE/airbnb/src/main/resources/data.sql
  BE/airbnb/src/main/resources/schema.sql
  BE/airbnb/src/test/java/mj/airbnb/AirbnbApplicationTests.java
  FE/.gitignore
  iOS/.gitignore
Labels: review-be

#26 [ 1팀 ] 시온 - DB설계 & 전체숙소목록보기와 숙소등록 기능 구현 리뷰 요청
  BE/airbnb/src/main/java/team01/airbnb/config/WebConfig.java
  BE/airbnb/src/main/java/team01/airbnb/controller/AccommodationController.java
  BE/airbnb/src/main/java/team01/airbnb/controller/UserController.java
  BE/airbnb/src/main/java/team01/airbnb/domain/Amenity.java
  BE/airbnb/src/main/java/team01/airbnb/domain/Reservation.java
  BE/airbnb/src/main/java/team01/airbnb/domain/User.java
  BE/airbnb/src/main/java/team01/airbnb/domain/accommodation/Accommodation.java
  BE/airbnb/src/main/java/team01/airbnb/domain/accommodation/AccommodationAddress.java
  BE/airbnb/src/main/java/team01/airbnb/domain/accommodation/AccommodationCondition.java
  BE/airbnb/src/main/java/team01/airbnb/domain/accommodation/AccommodationPhoto.java
  BE/airbnb/src/main/java/team01/airbnb/dto/Charge.java
  BE/airbnb/src/main/java/team01/airbnb/dto/OAuthToken.java
  BE/airbnb/src/main/java/team01/airbnb/dto/kakaoOauth/KakaoLogout.java
  BE/airbnb/src/main/java/team01/airbnb/dto/kakaoOauth/KakaoProfile.java
  BE/airbnb/src/main/java/team01/airbnb/dto/kakaoOauth/OAuthToken.java
  BE/airbnb/src/main/java/team01/airbnb/dto/request/AccommodationSaveRequestDto.java
  BE/airbnb/src/main/java/team01/airbnb/dto/request/ConditionSaveRequestDto.java
  BE/airbnb/src/main/java/team01/airbnb/dto/request/TotalAccommodationSaveRequestDto.java
  BE/airbnb/src/main/java/team01/airbnb/dto/response/AccommodationResponseDto.java
  BE/airbnb/src/main/java/team01/airbnb/exception/ConditionNotFoundException.java
  BE/airbnb/src/main/java/team01/airbnb/exception/NoResultSetException.java
  BE/airbnb/src/main/java/team01/airbnb/exceptionHandler/GlobalExceptionHandler.java
  BE/airbnb/src/main/java/team01/airbnb/repository/AccommodationRepository.java
  BE/airbnb/src/main/java/team01/airbnb/service/AccommodationService.java
  BE/airbnb/src/main/java/team01/airbnb/service/UserService.java
  BE/airbnb/src/main/resources/data.sql
  BE/airbnb/src/main/resources/schema.sql
  BE/airbnb/src/main/resources/templates/form.html
  BE/airbnb/src/main/resources/templates/index.html
  BE/airbnb/src/test/java/team01/airbnb/repository/AccommodationRepositoryTest.java
Labels: review-be

#19 [Team07 - Neo] 검색 기능 및 화면 구현, 네트워크 구성 추가
  iOS/airBnb/airBnb.xcodeproj/project.pbxproj
  iOS/airBnb/airBnb.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/airBnb/airBnb.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/airBnb/airBnb/AppCycle/AppDelegate.swift
  iOS/airBnb/airBnb/AppCycle/SceneDelegate.swift
  iOS/airBnb/airBnb/Assets.xcassets/AccentColor.colorset/Contents.json
  iOS/airBnb/airBnb/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/airBnb/airBnb/Assets.xcassets/BoardColor.colorset/Contents.json
  iOS/airBnb/airBnb/Assets.xcassets/CityColor.colorset/Contents.json
  iOS/airBnb/airBnb/Assets.xcassets/Contents.json
  iOS/airBnb/airBnb/Assets.xcassets/DistanceColor.colorset/Contents.json
  iOS/airBnb/airBnb/Assets.xcassets/MainImage.imageset/Contents.json
  iOS/airBnb/airBnb/Assets.xcassets/MainImage.imageset/MainImage-1.png
  iOS/airBnb/airBnb/Assets.xcassets/MainImage.imageset/MainImage-2.png
  iOS/airBnb/airBnb/Assets.xcassets/MainImage.imageset/MainImage.png
  iOS/airBnb/airBnb/Assets.xcassets/SelectedRangeColor.colorset/Contents.json
  iOS/airBnb/airBnb/Assets.xcassets/locationPoint.imageset/Contents.json
  iOS/airBnb/airBnb/Assets.xcassets/locationPoint.imageset/locationPoint2-1.png
  iOS/airBnb/airBnb/Assets.xcassets/locationPoint.imageset/locationPoint2-2.png
  iOS/airBnb/airBnb/Assets.xcassets/locationPoint.imageset/locationPoint2.png
  iOS/airBnb/airBnb/Base.lproj/LaunchScreen.storyboard
  iOS/airBnb/airBnb/CalendarHelper.swift
  iOS/airBnb/airBnb/CalendarManager.swift
  iOS/airBnb/airBnb/Extension/DateFormatter+Extension.swift
  iOS/airBnb/airBnb/Info.plist
  iOS/airBnb/airBnb/Model/SearchLocation.swift
  iOS/airBnb/airBnb/Network/Endpoint.swift
  iOS/airBnb/airBnb/Network/HTTPMethod.swift
  iOS/airBnb/airBnb/Network/NetworkError.swift
  iOS/airBnb/airBnb/Network/NetworkManager.swift
  iOS/airBnb/airBnb/SearchManager.swift
  iOS/airBnb/airBnb/UseCase/SearchLocationUseCase.swift
  iOS/airBnb/airBnb/View/CalendarDayCell.swift
  iOS/airBnb/airBnb/View/CalendarHeaderView.swift
  iOS/airBnb/airBnb/View/LocationCell.swift
  iOS/airBnb/airBnb/View/LocationHeaderView.swift
  iOS/airBnb/airBnb/View/LocationResultCell.swift
  iOS/airBnb/airBnb/ViewController/Calendar/Calendar.storyboard
  iOS/airBnb/airBnb/ViewController/Calendar/CalendarDataSource.swift
  iOS/airBnb/airBnb/ViewController/Calendar/CalendarViewController.swift
  iOS/airBnb/airBnb/ViewController/LocationSearch/LocationResultViewController.swift
  iOS/airBnb/airBnb/ViewController/LocationSearch/LocationSearchViewController.swift
  iOS/airBnb/airBnb/ViewController/Main/Base.lproj/Main.storyboard
  iOS/airBnb/airBnb/ViewController/Main/MainViewController.swift
  iOS/airBnb/airBnb/ViewModel/SearchLocationViewModel.swift
Labels: review-iOS

#39 [Team17 / BE] 숙소 조회, 검색 기능
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/codesquad/team17/gnb/GnbApplication.java
  BE/src/main/java/codesquad/team17/gnb/exception/NotFoundException.java
  BE/src/main/java/codesquad/team17/gnb/place/controller/PlaceController.java
  BE/src/main/java/codesquad/team17/gnb/place/domain/Location.java
  BE/src/main/java/codesquad/team17/gnb/place/domain/Option.java
  BE/src/main/java/codesquad/team17/gnb/place/domain/Place.java
  BE/src/main/java/codesquad/team17/gnb/place/dto/LocationDto.java
  BE/src/main/java/codesquad/team17/gnb/place/dto/OptionDto.java
  BE/src/main/java/codesquad/team17/gnb/place/dto/PlaceQueries.java
  BE/src/main/java/codesquad/team17/gnb/place/dto/PlaceSummary.java
  BE/src/main/java/codesquad/team17/gnb/place/repository/JdbcPlaceRepository.java
  BE/src/main/java/codesquad/team17/gnb/place/repository/PlaceRepository.java
  BE/src/main/java/codesquad/team17/gnb/place/repository/PlaceSql.groovy
  BE/src/main/java/codesquad/team17/gnb/place/service/PlaceService.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/schema.sql
  BE/src/test/java/codesquad/team17/gnb/GnbApplicationTests.java
  BE/src/test/java/codesquad/team17/gnb/place/repository/PlaceRepositoryTest.java
  BE/src/test/resources/data.sql
  README.md
Labels: review-be

#47 [Team-22 / BE] H2 대신 Redis 를 사용하여 로그인 세션 구현
  .gitignore
  backend/README.md
  backend/docker/Dockerfile.pyrodb
  backend/docker/README.md
  backend/docker/docker-compose.yml
  backend/docker/docker-start.sh
  backend/server/.gitignore
  backend/server/build.gradle
  backend/server/run.sh
  backend/server/src/main/java/com/airbnb/config/CorsConfig.java
  backend/server/src/main/java/com/airbnb/config/RedisConfig.java
  backend/server/src/main/java/com/airbnb/dao/TokenDao.java
  backend/server/src/main/java/com/airbnb/dao/UserDao.java
  backend/server/src/main/java/com/airbnb/dao/datasource/DataSource.java
  backend/server/src/main/java/com/airbnb/dao/datasource/PersistentDataSource.java
  backend/server/src/main/java/com/airbnb/dao/datasource/SessionDataSource.java
  backend/server/src/main/java/com/airbnb/domain/Auth.java
  backend/server/src/main/java/com/airbnb/intercepter/LoginInterceptor.java
  backend/server/src/main/java/com/airbnb/repository/AuthRepository.java
  backend/server/src/main/java/com/airbnb/repository/UserRepository.java
  backend/server/src/main/java/com/airbnb/service/AuthService.java
  backend/server/src/main/java/com/airbnb/service/UserService.java
  backend/server/src/main/resources/application.properties
  backend/server/src/main/resources/schema.sql
Labels: review-be

#55 [Team-20 FE/Jenny /Tami ] 캘린더, 요금, 인원 UI 및 data 구현
  FE/airbnb-fe/package-lock.json
  FE/airbnb-fe/package.json
  FE/airbnb-fe/src/App.js
  FE/airbnb-fe/src/components/Atoms/Modal/CheckModal/CalendarCarousel/Calendar.jsx
  FE/airbnb-fe/src/components/Atoms/Modal/CheckModal/CalendarCarousel/DayViewTR.jsx
  FE/airbnb-fe/src/components/Atoms/Modal/CheckModal/CalendarCarousel/SingleCalendar.jsx
  FE/airbnb-fe/src/components/Atoms/Modal/CheckModal/CalendarCarousel/YearMonth.jsx
  FE/airbnb-fe/src/components/Atoms/Modal/CheckModal/CalendarCarousel/createMonthArray.js
  FE/airbnb-fe/src/components/Atoms/Modal/CheckModal/CalendarCarousel/index.jsx
  FE/airbnb-fe/src/components/Atoms/Modal/CheckModal/index.jsx
  FE/airbnb-fe/src/components/Atoms/Modal/PeopleModal/PeopleCard.jsx
  FE/airbnb-fe/src/components/Atoms/Modal/PeopleModal/index.jsx
  FE/airbnb-fe/src/components/Atoms/Modal/PriceModal/PriceChart.jsx
  FE/airbnb-fe/src/components/Atoms/Modal/PriceModal/PriceDescription.jsx
  FE/airbnb-fe/src/components/Atoms/Modal/PriceModal/Slider.jsx
  FE/airbnb-fe/src/components/Atoms/Modal/PriceModal/index.jsx
  FE/airbnb-fe/src/components/Atoms/Search/Check/index.jsx
  FE/airbnb-fe/src/components/Atoms/Search/People/index.jsx
  FE/airbnb-fe/src/components/Atoms/Search/Price/PriceChart.jsx
  FE/airbnb-fe/src/components/Atoms/Search/Price/PriceModal/PriceChart.jsx
  FE/airbnb-fe/src/components/Atoms/Search/Price/index.jsx
  FE/airbnb-fe/src/components/Atoms/Search/SearchBtn/SearchButtonSvg.jsx
  FE/airbnb-fe/src/components/Atoms/Search/SearchBtn/index.jsx
  FE/airbnb-fe/src/components/Atoms/Search/index.jsx
  FE/airbnb-fe/src/components/Home/HeroSection/Header/AccountMenu/index.jsx
  FE/airbnb-fe/src/components/Home/HeroSection/Header/index.jsx
  FE/airbnb-fe/src/components/Home/TourSection/RoomTour/index.jsx
  FE/airbnb-fe/src/components/Home/TourSection/index.jsx
  FE/airbnb-fe/src/components/Reservation/index.jsx
  FE/airbnb-fe/src/components/utils/API.js
  FE/airbnb-fe/src/components/utils/mock/people-type.json
  FE/airbnb-fe/src/components/utils/mock/point.js
  FE/airbnb-fe/src/components/utils/reducer/priceReducer.js
  FE/airbnb-fe/yarn.lock
Labels: review-fe

#49 [Team02 / eve] 캘린더 기능 구현
  FE/airbnb/.gitignore
  FE/airbnb/README.md
  FE/airbnb/package-lock.json
  FE/airbnb/package.json
  FE/airbnb/public/favicon.ico
  FE/airbnb/public/index.html
  FE/airbnb/src/App.tsx
  FE/airbnb/src/assets/check.svg
  FE/airbnb/src/assets/left_arrow.svg
  FE/airbnb/src/assets/logo.png
  FE/airbnb/src/assets/menu.svg
  FE/airbnb/src/assets/minus.svg
  FE/airbnb/src/assets/minus_circle.svg
  FE/airbnb/src/assets/pause_circle.svg
  FE/airbnb/src/assets/plus.svg
  FE/airbnb/src/assets/plus_circle.svg
  FE/airbnb/src/assets/right_arrow.svg
  FE/airbnb/src/assets/search.svg
  FE/airbnb/src/assets/user.svg
  FE/airbnb/src/assets/wish.svg
  FE/airbnb/src/assets/x_circle.svg
  FE/airbnb/src/component/Header.tsx
  FE/airbnb/src/component/PrimarySection.tsx
  FE/airbnb/src/component/header/Logo.tsx
  FE/airbnb/src/component/header/Menus.tsx
  FE/airbnb/src/component/header/MyPage.tsx
  FE/airbnb/src/component/header/MyPageModal.tsx
  FE/airbnb/src/component/searchBar/BigSearchBar.tsx
  FE/airbnb/src/component/searchBar/Fare.tsx
  FE/airbnb/src/component/searchBar/Guest.tsx
  FE/airbnb/src/component/searchBar/Period.tsx
  FE/airbnb/src/component/searchBar/SearchBtn.tsx
  FE/airbnb/src/component/searchBar/calendar/Calendar.tsx
  FE/airbnb/src/component/searchBar/calendar/CalendarModal.tsx
  FE/airbnb/src/component/searchBar/calendar/Day.tsx
  FE/airbnb/src/component/searchBar/calendar/getCalendarData.ts
  FE/airbnb/src/component/searchBar/fareChart/ChartCanvas.tsx
  FE/airbnb/src/component/searchBar/fareChart/FareModal.tsx
  FE/airbnb/src/component/searchBar/fareChart/chartType.ts
  FE/airbnb/src/component/searchBar/fareChart/getChartData.ts
  FE/airbnb/src/component/searchBar/fareChart/mockData.js
  FE/airbnb/src/component/searchBar/guestList/GuestListItem.tsx
  FE/airbnb/src/component/searchBar/guestList/GuestModal.tsx
  FE/airbnb/src/hooks/modalHooks.ts
  FE/airbnb/src/index.tsx
  FE/airbnb/src/pages/LandingPage.tsx
  FE/airbnb/src/pages/SearchResultPage.tsx
  FE/airbnb/src/pages/index.tsx
  FE/airbnb/src/react-app-env.d.ts
  FE/airbnb/src/state/atoms/calendarAtoms.ts
  FE/airbnb/src/styles/reset.css
  FE/airbnb/src/styles/theme.ts
  FE/airbnb/tsconfig.json
  FE/airbnb/yarn.lock
Labels: review-fe
