Repository codesquad-members-2021/airbnb, pull requests merged in 2021-06, with the labels that each got.

#63 [team-4 롤로] 커스텀 캘린더(UI + 모델) + DI 개선
  IOS/airbnb/airbnb.xcodeproj/project.pbxproj
  IOS/airbnb/airbnb/AccomodationConditions/CalendarSelect/CalendarViewController.swift
  IOS/airbnb/airbnb/AccomodationConditions/LocationSearch/ViewModel/PopularLocationLoadModel.swift
  IOS/airbnb/airbnb/AccomodationConditions/LocationSearch/ViewModel/SearchResultUpdateModel.swift
  IOS/airbnb/airbnb/AppCycle/SceneDelegate.swift
  IOS/airbnb/airbnb/Main/Base.lproj/Main.storyboard
  IOS/airbnb/airbnb/Main/ViewController/HomeViewController.swift
  IOS/airbnb/airbnb/Main/ViewModel/HomeViewModel.swift
  IOS/airbnb/airbnb/Main/ViewModel/ImagePathLoadModel.swift
  IOS/airbnb/airbnb/Network/Fake/FakeNetworkManager.swift
  iOS/airbnb/airbnb/AccommodationConditions/AccommodationConditions.storyboard
  iOS/airbnb/airbnb/AccommodationConditions/CalendarSelect/Model/CalendarCoordinate.swift
  iOS/airbnb/airbnb/AccommodationConditions/CalendarSelect/Model/CalendarManager.swift
  iOS/airbnb/airbnb/AccommodationConditions/CalendarSelect/Model/DateSelectionManager.swift
  iOS/airbnb/airbnb/AccommodationConditions/CalendarSelect/Model/Day.swift
  iOS/airbnb/airbnb/AccommodationConditions/CalendarSelect/Model/Month.swift
  iOS/airbnb/airbnb/AccommodationConditions/CalendarSelect/Model/SelectStatus.swift
  iOS/airbnb/airbnb/AccommodationConditions/CalendarSelect/View/AccommodationConditionTableViewCell.swift
  iOS/airbnb/airbnb/AccommodationConditions/CalendarSelect/View/CalendarCollectionViewCell.swift
  iOS/airbnb/airbnb/AccommodationConditions/CalendarSelect/View/MonthHeaderCollectionViewCell.swift
  iOS/airbnb/airbnb/AccommodationConditions/CalendarSelect/ViewController/AccommodationConditionTableViewDataSource.swift
  iOS/airbnb/airbnb/AccommodationConditions/CalendarSelect/ViewController/CalendarCollectionViewDataSource.swift
  iOS/airbnb/airbnb/AccommodationConditions/CalendarSelect/ViewController/CalendarViewController.swift
  iOS/airbnb/airbnb/AccommodationConditions/CalendarSelect/ViewModel/CalendarManageModel.swift
  iOS/airbnb/airbnb/AccommodationConditions/CalendarSelect/ViewModel/CalendarViewModel.swift
  iOS/airbnb/airbnb/AccommodationConditions/CommonModels/Charge.swift
  iOS/airbnb/airbnb/AccommodationConditions/CommonModels/ConditionManager.swift
  iOS/airbnb/airbnb/AccommodationConditions/CommonModels/Location.swift
  iOS/airbnb/airbnb/AccommodationConditions/CommonModels/Period.swift
  iOS/airbnb/airbnb/AccommodationConditions/LocationSearch/Model/PopularLocation.swift
  iOS/airbnb/airbnb/AccommodationConditions/LocationSearch/UseCase/PopularLocationLoadUseCase.swift
  iOS/airbnb/airbnb/AccommodationConditions/LocationSearch/UseCase/PopularLocationUseCase.swift
  iOS/airbnb/airbnb/AccommodationConditions/LocationSearch/UseCase/SearchResultFetchUseCase.swift
  iOS/airbnb/airbnb/AccommodationConditions/LocationSearch/UseCase/SearchResultUseCase.swift
  iOS/airbnb/airbnb/AccommodationConditions/LocationSearch/View/PopularLocationTableViewCell.swift
  iOS/airbnb/airbnb/AccommodationConditions/LocationSearch/View/SearchResultTableViewCell.swift
  iOS/airbnb/airbnb/AccommodationConditions/LocationSearch/ViewController/LocationSearchController.swift
  iOS/airbnb/airbnb/AccommodationConditions/LocationSearch/ViewController/LocationSearchResultUpdating.swift
  iOS/airbnb/airbnb/AccommodationConditions/LocationSearch/ViewController/PopularLocationTableViewDataSource.swift
  iOS/airbnb/airbnb/AccommodationConditions/LocationSearch/ViewController/PopularLocationViewController.swift
  iOS/airbnb/airbnb/AccommodationConditions/LocationSearch/ViewController/SearchResultTableViewController.swift
  iOS/airbnb/airbnb/AccommodationConditions/LocationSearch/ViewController/SearchResultTableViewDataSource.swift
  iOS/airbnb/airbnb/AccommodationConditions/LocationSearch/ViewModel/PopularLocationViewModel.swift
  iOS/airbnb/airbnb/AccommodationConditions/LocationSearch/ViewModel/SearchResultUpdateModel.swift
  iOS/airbnb/airbnb/AccommodationConditions/LocationSearch/ViewModel/SearchResultViewModel.swift
  iOS/airbnb/airbnb/CommonInterfaces/AnyResultHandleModel.swift
  iOS/airbnb/airbnb/CommonInterfaces/AnySearchConditionHandleModel.swift
  iOS/airbnb/airbnb/CommonInterfaces/NetworkResultHandleModel.swift
  iOS/airbnb/airbnb/CommonInterfaces/SearchConditionHandleModel.swift
  iOS/airbnb/airbnb/DIContainer/HomeDIContainer.swift
  iOS/airbnb/airbnb/Factory/DateFormatter.swift
  iOS/airbnb/airbnb/Factory/StoryboardFactory.swift
Labels: review-iOS

#58 [FE] 메인화면 요금차트, X버튼 구현
  FE/airbnb/.env.development
  FE/airbnb/.env.production
  FE/airbnb/package-lock.json
  FE/airbnb/package.json
  FE/airbnb/public/index.html
  FE/airbnb/src/App.tsx
  FE/airbnb/src/assets/image/hero-img.png
  FE/airbnb/src/assets/svg/Property 1=minus-circle.svg
  FE/airbnb/src/assets/svg/Property 1=plus-circle.svg
  FE/airbnb/src/assets/svg/Property 1=star.svg
  FE/airbnb/src/assets/svg/Property 1=x-circle.svg
  FE/airbnb/src/components/calendar/CalendarDate.tsx
  FE/airbnb/src/components/header/Background.tsx
  FE/airbnb/src/components/header/Header.tsx
  FE/airbnb/src/components/header/HoverBlock.tsx
  FE/airbnb/src/components/header/form/FormCheckIn.tsx
  FE/airbnb/src/components/header/form/FormCheckOut.tsx
  FE/airbnb/src/components/header/form/FormColumn.tsx
  FE/airbnb/src/components/header/form/FormGuest.tsx
  FE/airbnb/src/components/header/form/FormGuestToggle.tsx
  FE/airbnb/src/components/header/form/FormLocation.tsx
  FE/airbnb/src/components/header/form/FormPrice.tsx
  FE/airbnb/src/components/header/form/HeaderForm.tsx
  FE/airbnb/src/components/header/form/calendar/FormCalendar.tsx
  FE/airbnb/src/components/header/form/calendar/calendarDateFn.tsx
  FE/airbnb/src/components/header/form/guestToggle/FormGuestToggle.tsx
  FE/airbnb/src/components/header/form/guestToggle/GuestColumn.tsx
  FE/airbnb/src/components/header/form/guestToggle/guestType.ts
  FE/airbnb/src/components/header/form/priceBar/PriceBar.tsx
  FE/airbnb/src/components/header/form/priceBar/PriceChart.tsx
  FE/airbnb/src/components/header/form/priceBar/priceType.ts
  FE/airbnb/src/components/header/form/priceBar/sampleData.ts
  FE/airbnb/src/components/header/tab/HeaderTabList.tsx
  FE/airbnb/src/components/map/Map.tsx
  FE/airbnb/src/components/map/MapLabel.tsx
  FE/airbnb/src/components/reserveHeader/ReserveForm.tsx
  FE/airbnb/src/components/reserveHeader/ReserveHeader.tsx
  FE/airbnb/src/components/reserveRoomList/ReserveRoom.tsx
  FE/airbnb/src/components/reserveRoomList/ReserveRoomGrade.tsx
  FE/airbnb/src/components/reserveRoomList/ReserveRoomList.tsx
  FE/airbnb/src/components/reserveRoomList/ReserveRoomPrice.tsx
  FE/airbnb/src/components/reserveRoomList/RoomDescription.tsx
  FE/airbnb/src/components/reserveRoomList/roomType.ts
  FE/airbnb/src/components/util/util.ts
  FE/airbnb/src/index.css
  FE/airbnb/src/pages/MainPage.tsx
  FE/airbnb/src/pages/ReservePage.tsx
  FE/airbnb/src/recoil/calendarAtom.ts
  FE/airbnb/src/recoil/headerAtom.ts
  FE/airbnb/src/recoil/reserveRoomAtom.ts
  FE/airbnb/src/recoil/roomSampleData.ts
  FE/airbnb/src/util/api.ts
Labels: review-fe

#59 [ team 12 ] Calendar 라이브러리 제작 및 배포 완료
  .gitignore
  README.md
  README.old.md
  package-lock.json
  package.json
  public/favicon.ico
  public/hero.png
  public/img_location.webp
  public/index.html
  public/robots.txt
  src/App.js
  src/App.test.js
  src/assets/svg/img_hamberger.svg
  src/assets/svg/img_language.svg
  src/assets/svg/img_logo.svg
  src/assets/svg/img_myPage.svg
  src/assets/svg/img_search.svg
  src/components/header/Header.js
  src/components/header/MyPage.js
  src/components/header/menu/Menu.js
  src/components/header/menu/SearchForm.js
  src/components/header/menu/SearchInput.js
  src/components/header/menu/input/Chart.js
  src/components/header/menu/input/Guest.js
  src/components/home/Footer.js
  src/components/home/HomePage.js
  src/components/home/Location.js
  src/components/home/Thema.js
  src/components/search/SearchPage.js
  src/components/search/SearchResult.js
  src/index.css
  src/index.js
  src/lib/Test.tsx
  src/lib/calendar/Calendar.tsx
  src/lib/calendar/CalendarItem.tsx
  src/lib/calendar/CalendarProvider.tsx
  src/lib/calendar/CalendarReducer.ts
  src/lib/calendar/Day.tsx
  src/lib/carousel/Carousel.tsx
  src/lib/utils/constant.ts
  src/lib/utils/renderFn.tsx
  src/lib/utils/styled.ts
  src/lib/utils/types.tsx
  src/react-app-env.d.ts
  src/reportWebVitals.js
  src/setupTests.js
  src/utils/GlobalStyles.js
  src/utils/constant.js
  src/utils/dummy.js
  src/utils/fetchFn.js
  tsconfig.json
  yarn.lock
Labels: review-fe

#56 [Team-22 / FE (Daisy & Dico)] Github OAuth & 캘린더 구현중
  .gitignore
  backend/server/spring-log.txt
  frontend/.gitignore
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Header/Login.tsx
  frontend/src/components/Header/LoginModal.tsx
  frontend/src/components/SearchBar/Calendar/Calendar.tsx
  frontend/src/components/SearchBar/Calendar/CalendarModal.tsx
  frontend/src/components/SearchBar/Calendar/CalendarStyles.tsx
  frontend/src/components/SearchBar/Calendar/MonthlyCalendar.tsx
  frontend/src/components/SearchBar/Calendar/Old.md
  frontend/src/components/SearchBar/Guests/GuestStyles.tsx
  frontend/src/components/SearchBar/Guests/Guests.tsx
  frontend/src/components/SearchBar/Guests/GuestsModal.tsx
  frontend/src/components/SearchBar/RoomPrice/PriceGraph.tsx
  frontend/src/components/SearchBar/RoomPrice/PriceRange.tsx
  frontend/src/components/SearchBar/RoomPrice/Prices.json
  frontend/src/components/SearchBar/RoomPrice/RoomPrice.tsx
  frontend/src/components/SearchBar/RoomPrice/RoomPriceModal.tsx
  frontend/src/components/SearchBar/SearchBar.tsx
  frontend/src/components/SearchBar/SearchBarStyles.tsx
  frontend/src/components/SearchBar/SearchFilter.jsx
  frontend/src/components/common/Button.tsx
  frontend/src/components/common/CancelButton.tsx
  frontend/src/components/common/Logo.svg
  frontend/src/components/common/Responsive.jsx
  frontend/src/components/pages/LoadingPage.tsx
  frontend/src/components/pages/MainPage.tsx
  frontend/src/components/pages/ResultPage.tsx
  frontend/src/image/cancelBtn.svg
  frontend/src/image/largeSearchBtn.svg
  frontend/src/image/loginLogo.svg
  frontend/src/image/menu.svg
  frontend/src/image/minus.svg
  frontend/src/image/plus.svg
  frontend/src/image/sliderBtn.svg
  frontend/src/image/smallSearchBtn.svg
  frontend/src/index.css
  frontend/src/index.tsx
  frontend/src/react-app-env.d.ts
  frontend/src/recoil/AtomTypes.tsx
  frontend/src/recoil/Atoms.tsx
  frontend/src/util/Calendar.tsx
  frontend/src/util/enum.tsx
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: review-fe

#48 [Team03 iOS Elly] - Calendar, DiffableDataSource, Alamofire
  iOS/.gitignore
  iOS/airbnb.xcodeproj/project.pbxproj
  iOS/airbnb/AppDelegate.swift
  iOS/airbnb/CalendarPicker/CalendarViewController.swift
  iOS/airbnb/CalendarPicker/Model/CalendarDateCalculator.swift
  iOS/airbnb/CalendarPicker/Model/CalenderCollectionDataSource.swift
  iOS/airbnb/CalendarPicker/Model/Day.swift
  iOS/airbnb/CalendarPicker/Model/MonthMetadata.swift
  iOS/airbnb/CalendarPicker/View/CalendarDateCell.swift
  iOS/airbnb/CalendarPicker/View/CalendarHeader.swift
  iOS/airbnb/CalendarPicker/ViewModel/CalendarViewModel.swift
  iOS/airbnb/Extension/UIImageView+LoadFromURL.swift
  iOS/airbnb/FooterTable/FooterTableViewCell.swift
  iOS/airbnb/FooterTable/FooterTableViewController.swift
  iOS/airbnb/MainCoordinator.swift
  iOS/airbnb/Network/APIService.swift
  iOS/airbnb/Network/APIServiceError.swift
  iOS/airbnb/Network/EndPoint.swift
  iOS/airbnb/Network/Responses.swift
  iOS/airbnb/Network/TravelListAPI.swift
  iOS/airbnb/SceneDelegate.swift
  iOS/airbnb/Search/ContainerViewController.swift
  iOS/airbnb/Search/Model/NearPlace.swift
  iOS/airbnb/Search/Model/NearPlaceDTO.swift
  iOS/airbnb/Search/Model/NearPlaceDataSource.swift
  iOS/airbnb/Search/Model/ThemePlaceDataSource.swift
  iOS/airbnb/Search/Search.storyboard
  iOS/airbnb/Search/SearchCoordinator.swift
  iOS/airbnb/Search/SearchViewController.swift
  iOS/airbnb/Search/TravelListViewController.swift
  iOS/airbnb/Search/View/NearPlaceCell.swift
  iOS/airbnb/Search/View/NearPlaceCell.xib
Labels: review-iOS

#60 [iOS] BehaviorRelay, Frame
  Airbnb/.DS_Store
  Airbnb/Airbnb.xcodeproj/project.pbxproj
  Airbnb/Airbnb.xcodeproj/xcuserdata/ray.xcuserdatad/xcschemes/xcschememanagement.plist
  Airbnb/Airbnb.xcworkspace/xcuserdata/ray.xcuserdatad/UserInterfaceState.xcuserstate
  Airbnb/Airbnb/.DS_Store
  Airbnb/Airbnb/Data/Model/AccommodationInfo.swift
  Airbnb/Airbnb/Data/Model/DataManager.swift
  Airbnb/Airbnb/Data/Model/LoginInfo.swift
  Airbnb/Airbnb/Data/Model/MainViewInfo.swift
  Airbnb/Airbnb/Data/Model/TransformManager.swift
  Airbnb/Airbnb/Presenter/Controller/CalendarViewController.swift
  Airbnb/Airbnb/Presenter/Controller/Delegate/MainCollectionViewDelegate.swift
  Airbnb/Airbnb/Presenter/Controller/Delegate/RxDelegateProxy.swift
  Airbnb/Airbnb/Presenter/Controller/GuestViewController.swift
  Airbnb/Airbnb/Presenter/Controller/LoginViewContoller.swift
  Airbnb/Airbnb/Presenter/Controller/MainViewController.swift
  Airbnb/Airbnb/Presenter/Controller/PriceViewController.swift
  Airbnb/Airbnb/Presenter/Controller/SearchViewController.swift
  Airbnb/Airbnb/Presenter/Storyboard/Base.lproj/Main.storyboard
  Airbnb/Airbnb/Presenter/View/Cell/CalendarCell.swift
  Airbnb/Airbnb/Presenter/View/Cell/FirstSectionCell.swift
  Airbnb/Airbnb/Presenter/View/Cell/RegieonInfoCell.swift
  Airbnb/Airbnb/Presenter/View/Cell/SecondSectionCell.swift
  Airbnb/Airbnb/Presenter/View/Cell/ThirdSectionCell.swift
  Airbnb/Airbnb/Presenter/View/Cell/TravelInfoCell.swift
  Airbnb/Airbnb/Presenter/View/FirstSectionView.swift
  Airbnb/Airbnb/Presenter/View/GraphView.swift
  Airbnb/Airbnb/Presenter/View/HeaderView.swift
  Airbnb/Airbnb/Presenter/View/LogInView.swift
  Airbnb/Airbnb/Presenter/View/SecondSectionView.swift
  Airbnb/Airbnb/Presenter/View/ThirdSectionView.swift
  Airbnb/Airbnb/Presenter/ViewModel/CalendarViewModel.swift
  Airbnb/Airbnb/Presenter/ViewModel/CommonViewModelType.swift
  Airbnb/Airbnb/Presenter/ViewModel/GuestViewModel.swift
  Airbnb/Airbnb/Presenter/ViewModel/MainViewModel.swift
  Airbnb/Airbnb/Presenter/ViewModel/PriceViewModel.swift
  Airbnb/Airbnb/Presenter/ViewModel/RegieonViewModel.swift
  Airbnb/Airbnb/Presenter/ViewModel/TravelInfoViewModel.swift
  Airbnb/Airbnb/Service/APIService.swift
  Airbnb/Podfile
  Airbnb/Podfile.lock
  Airbnb/Pods/Manifest.lock
  Airbnb/Pods/Pods.xcodeproj/project.pbxproj
  Airbnb/Pods/Pods.xcodeproj/xcuserdata/ray.xcuserdatad/xcschemes/xcschememanagement.plist
  Airbnb/Pods/Target Support Files/Pods-Airbnb/Pods-Airbnb-acknowledgements.markdown
  Airbnb/Pods/Target Support Files/Pods-Airbnb/Pods-Airbnb-acknowledgements.plist
  Airbnb/Pods/Target Support Files/Pods-Airbnb/Pods-Airbnb-frameworks-Debug-input-files.xcfilelist
  Airbnb/Pods/Target Support Files/Pods-Airbnb/Pods-Airbnb-frameworks-Debug-output-files.xcfilelist
  Airbnb/Pods/Target Support Files/Pods-Airbnb/Pods-Airbnb-frameworks-Release-input-files.xcfilelist
  Airbnb/Pods/Target Support Files/Pods-Airbnb/Pods-Airbnb-frameworks-Release-output-files.xcfilelist
  Airbnb/Pods/Target Support Files/Pods-Airbnb/Pods-Airbnb-frameworks.sh
  Airbnb/Pods/Target Support Files/Pods-Airbnb/Pods-Airbnb.debug.xcconfig
  Airbnb/Pods/Target Support Files/Pods-Airbnb/Pods-Airbnb.release.xcconfig
Labels: review-iOS

#61 [Team18 - Min, ZG (iOS)] 조건 설정 화면 완성, 숙소 검색화면 완성
  iOS/airbnb/airbnb.xcodeproj/project.pbxproj
  iOS/airbnb/airbnb.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  iOS/airbnb/airbnb/Base.lproj/Main.storyboard
  iOS/airbnb/airbnb/Controller/FindingAccommdationViewController.swift
  iOS/airbnb/airbnb/Controller/FindingAccommodationTableViewDataSource.swift
  iOS/airbnb/airbnb/Controller/RecommendTripCollectionViewDataSource.swift
  iOS/airbnb/airbnb/Controller/RoomInformationViewController.swift
  iOS/airbnb/airbnb/Controller/RoomInformationViewDataSource.swift
  iOS/airbnb/airbnb/Controller/SearchViewController.swift
  iOS/airbnb/airbnb/Controller/SuggestionsTableViewController.swift
  iOS/airbnb/airbnb/Controller/TripPlaceCollectionViewDataSource.swift
  iOS/airbnb/airbnb/Controller/ViewController.swift
  iOS/airbnb/airbnb/Extension/ImageView+Extension.swift
  iOS/airbnb/airbnb/Extension/Notification.swift
  iOS/airbnb/airbnb/Model/Data/ConditionPageData/CostGraph.swift
  iOS/airbnb/airbnb/Model/Data/ConditionPageData/FindingAccommdationCondition.swift
  iOS/airbnb/airbnb/Model/Data/FirstPageData/RecommendTrip.swift
  iOS/airbnb/airbnb/Model/Data/FirstPageData/TripPlace.swift
  iOS/airbnb/airbnb/Model/Data/FirstPageData/WishList.swift
  iOS/airbnb/airbnb/Model/Data/SearchResultData/RoomData.swift
  iOS/airbnb/airbnb/Model/Data/SearchResultData/RoomEntity.swift
  iOS/airbnb/airbnb/Model/Data/SearchResultData/SearchResult.swift
  iOS/airbnb/airbnb/Model/Data/SearchResultData/SearchResultData.swift
  iOS/airbnb/airbnb/Model/Network/EndPoint.swift
  iOS/airbnb/airbnb/Model/Network/MainPageDTO.swift
  iOS/airbnb/airbnb/Model/Network/Network.swift
  iOS/airbnb/airbnb/View/CalendarView.swift
  iOS/airbnb/airbnb/View/ChartGraph/ChartDefault.swift
  iOS/airbnb/airbnb/View/ChartGraph/CubicChart.swift
  iOS/airbnb/airbnb/View/ChartGraph/Env.swift
  iOS/airbnb/airbnb/View/ChartGraph/RangeSlider.swift
  iOS/airbnb/airbnb/View/ChartGraph/RangeSliderTrackLayer.swift
  iOS/airbnb/airbnb/View/CostGraphView.swift
  iOS/airbnb/airbnb/View/FindingAccommodationTableViewCell.swift
  iOS/airbnb/airbnb/View/FindingAccommodationViewTableViewCell.swift
  iOS/airbnb/airbnb/View/RecommendTripCollectionViewCell.swift
  iOS/airbnb/airbnb/View/RoomInformationCell.swift
  iOS/airbnb/airbnb/View/SearchTableViewCell.swift
  iOS/airbnb/airbnb/View/TripPlaceCollectionViewCell.swift
Labels: review-iOS

#71 [Team-01 iOS] GuestNumber 설정 뷰에서 숙소 선택 화면으로 가는 동작 구현과 View와 View 모델 분리
  iOS/AirBed&Breakfast/AirBed&Breakfast.xcodeproj/project.pbxproj
  iOS/AirBed&Breakfast/AirBed&Breakfast/Application/DIContainer/ReservationDetailViewControllerDIContainer.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Application/NotificationNameExtension.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Domain/GuestType.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/Controllers/AccommodationSelectViewController.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/Controllers/ReservationDetailViewController.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/Controllers/SearchViewController.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/Controllers/SetUpViewController.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/Controllers/ViewModel/ReservationDetailViewModel.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/Base.lproj/Main.storyboard
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/CalendarView/CalendarControlView.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/CalendarView/CalendarControlViewModel.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/NumberOfHeadSelectionView/GuestNumberSelectionView.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/NumberOfHeadSelectionView/NumberAdjustmentView/NumberAdjustmentView.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/PriceSlideView/PriceSlideControlView.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/PriceSlideView/PriceSlideControlViewModel.swift
  iOS/AirBed&Breakfast/AirBed&Breakfast/Presentation/View/PriceSlideView/RangeSlider.swift
Labels: review-iOS

#65 [team10 FE Luke]모달/캘린더/인원 구현
  frontend/front-airbnb/.gitignore
  frontend/front-airbnb/README.md
  frontend/front-airbnb/package-lock.json
  frontend/front-airbnb/package.json
  frontend/front-airbnb/public/favicon.ico
  frontend/front-airbnb/public/index.html
  frontend/front-airbnb/public/logo192.png
  frontend/front-airbnb/public/logo512.png
  frontend/front-airbnb/public/manifest.json
  frontend/front-airbnb/public/robots.txt
  frontend/front-airbnb/src/App.css
  frontend/front-airbnb/src/App.js
  frontend/front-airbnb/src/App.test.js
  frontend/front-airbnb/src/Context.js
  frontend/front-airbnb/src/components/mainPage/Main.jsx
  frontend/front-airbnb/src/components/mainPage/header/Header.jsx
  frontend/front-airbnb/src/components/mainPage/header/Logo.jsx
  frontend/front-airbnb/src/components/mainPage/header/Menu.jsx
  frontend/front-airbnb/src/components/mainPage/header/MyPage.jsx
  frontend/front-airbnb/src/components/modal/Calendar.jsx
  frontend/front-airbnb/src/components/modal/CalendarModal.jsx
  frontend/front-airbnb/src/components/modal/Modal.jsx
  frontend/front-airbnb/src/components/modal/PersonnelModal.jsx
  frontend/front-airbnb/src/components/modal/PriceModal.jsx
  frontend/front-airbnb/src/components/resultPage/MapBox.jsx
  frontend/front-airbnb/src/components/resultPage/ResultBox.jsx
  frontend/front-airbnb/src/components/resultPage/ResultPage.jsx
  frontend/front-airbnb/src/components/searchBar/CloseButton.jsx
  frontend/front-airbnb/src/components/searchBar/Period.jsx
  frontend/front-airbnb/src/components/searchBar/Personnel.jsx
  frontend/front-airbnb/src/components/searchBar/Price.jsx
  frontend/front-airbnb/src/components/searchBar/SearchBar.jsx
  frontend/front-airbnb/src/components/searchBar/SearchButton.jsx
  frontend/front-airbnb/src/index.css
  frontend/front-airbnb/src/index.js
  frontend/front-airbnb/src/logo.svg
  frontend/front-airbnb/src/reportWebVitals.js
  frontend/front-airbnb/src/setupTests.js
  frontend/front-airbnb/src/style/GlobalStyle.jsx
  frontend/front-airbnb/src/style/theme.js
  frontend/front-airbnb/yarn.lock
Labels: review-fe

#67 [ FE - Team-03 ] 검색페이지 구현
  FE/client/craco.config.js
  FE/client/package.json
  FE/client/src/App.tsx
  FE/client/src/Components/GNB/Nav.tsx
  FE/client/src/Components/GNB/SearchMapNav.tsx
  FE/client/src/Components/GNB/index.tsx
  FE/client/src/Components/HotelList/HotelItem.tsx
  FE/client/src/Components/HotelList/HotelListHeader.tsx
  FE/client/src/Components/HotelList/ReservationModal/ReservationModal.tsx
  FE/client/src/Components/HotelList/ReservationModal/ReservationPrices.tsx
  FE/client/src/Components/HotelList/ReservationModal/ReservationUserInfo.tsx
  FE/client/src/Components/HotelList/index.tsx
  FE/client/src/Components/Modal/Calendar.tsx
  FE/client/src/Components/Modal/ChargeModal.tsx
  FE/client/src/Components/Modal/Graph.tsx
  FE/client/src/Components/Modal/LocationItem.tsx
  FE/client/src/Components/Modal/LocationModal.tsx
  FE/client/src/Components/Modal/Month.tsx
  FE/client/src/Components/Modal/PersonnelModal.tsx
  FE/client/src/Components/Modal/Slider.tsx
  FE/client/src/Components/Modal/index.tsx
  FE/client/src/Components/Pages/MainPage.tsx
  FE/client/src/Components/Pages/Page404.tsx
  FE/client/src/Components/Pages/SearchMapPage.tsx
  FE/client/src/Components/SearchBar/Charge.tsx
  FE/client/src/Components/SearchBar/DateKind.tsx
  FE/client/src/Components/SearchBar/EntryDate.tsx
  FE/client/src/Components/SearchBar/Location.tsx
  FE/client/src/Components/SearchBar/Personnel.tsx
  FE/client/src/Components/SearchBar/SearchButton.tsx
  FE/client/src/Components/SearchBar/index.tsx
  FE/client/src/Components/SearchMap/index.tsx
  FE/client/src/Components/commons/base.jsx
  FE/client/src/Components/commons/baseType.tsx
  FE/client/src/Components/commons/searchBarType.tsx
  FE/client/src/Images/star.svg
  FE/client/src/recoil/atoms.tsx
  FE/client/src/recoil/fetchAtoms.tsx
  FE/client/src/utils/calendarUtil.tsx
  FE/client/src/utils/graphData.js
  FE/client/src/utils/graphUtil.tsx
  FE/client/src/utils/serviceUtils.tsx
  FE/client/tsconfig.json
  FE/client/tsconfig.paths.json
  FE/client/yarn.lock
Labels: review-fe

#72 [BE] 숙소 조회 도메인 및 테스트
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/controller/AccommodationController.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/controller/AccommodationDetailResponse.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/controller/AccommodationDetailResponseBuilder.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/controller/AccommodationHost.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/controller/AccommodationPriceStats.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/controller/AccommodationRequest.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/controller/AccommodationRequestBuilder.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/controller/AccommodationRequestDTO.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/controller/AccommodationReservationInfo.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/controller/AccommodationReservationInfoBuilder.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/controller/AccommodationResponse.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/controller/AccommodationResponseBuilder.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/controller/AccommodationResponseDTO.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/controller/AccommodationResponseDTOBuilder.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/domain/Accommodation.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/domain/AccommodationBuilder.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/domain/AccommodationOption.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/domain/AccommodationOptionBuilder.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/domain/price/AccommodationTaxPolicy.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/domain/price/CleaningFeePolicy.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/domain/price/DiscountPolicy.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/domain/price/Price.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/domain/price/PricePolicies.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/domain/price/PricePolicy.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/domain/price/PriceUtils.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/domain/price/ServiceFeePolicy.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/domain/price/WeekdayDiscountPolicy.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/domain/price/Weekdays.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/repository/AccommodationRepository.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/service/AccommodationService.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/service/AccommodationServiceImpl.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/accommodation/service/AccommodationServiceMockup.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/common/dummydata/AccommodationDTODummyDataFactory.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/common/dummydata/AccommodationDummyDataFactory.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/common/dummydata/AccommodationHostDummyDataFactory.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/common/dummydata/AccommodationOptionDummyDataFactory.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/common/dummydata/AccommodationPriceStatsDummyDataFactory.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/common/dummydata/AccommodationReservationInfoDummyDataFactory.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/common/dummydata/AccommodationResponseDummyDataFactory.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/common/dummydata/ReservationDTODummyDataFactory.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/common/dummydata/ReservationDetailDummyDataFactory.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/common/dummydata/WishlistItemDTODummyDataFactory.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/common/exception/NotFoundException.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/common/utils/DummyDataFactory.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/reservation/controller/ReservationController.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/reservation/controller/ReservationDTO.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/reservation/domain/Reservation.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/reservation/domain/ReservationDetail.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/reservation/domain/ReservationDetailBuilder.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/wishlist/WishlistController.java
  BE/airbnb-be/src/main/java/com/codesquad/airbnb/wishlist/WishlistItemDTO.java
  BE/airbnb-be/src/test/java/com/codesquad/airbnb/accommodation/controller/AccommodationControllerTest.java
  BE/airbnb-be/src/test/java/com/codesquad/airbnb/accommodation/domain/price/WeekdaysTest.java
  BE/airbnb-be/src/test/java/com/codesquad/airbnb/accommodation/service/AccommodationServiceImplTest.java
  BE/airbnb-be/src/test/java/com/codesquad/airbnb/reservation/controller/ReservationControllerTest.java
  BE/airbnb-be/src/test/java/com/codesquad/airbnb/wishlist/WishlistControllerTest.java
Labels: review-be

#69 [ team-4 / Autumn ] 날짜 선택, 인원 선택, 요금 모달의 슬라이더, 검색 화면 숙소 리스트, 지도
  FE/fe-airbnb/.env
  FE/fe-airbnb/.gitignore
  FE/fe-airbnb/package-lock.json
  FE/fe-airbnb/package.json
  FE/fe-airbnb/public/pause-circle.svg
  FE/fe-airbnb/src/App.tsx
  FE/fe-airbnb/src/HotelListDataType.ts
  FE/fe-airbnb/src/components/MinusButton.tsx
  FE/fe-airbnb/src/components/PlusButton.tsx
  FE/fe-airbnb/src/components/SearchButton.jsx
  FE/fe-airbnb/src/components/calendar/Calendar.jsx
  FE/fe-airbnb/src/components/calendar/CalendarHeader.jsx
  FE/fe-airbnb/src/components/calendar/CalendarList.jsx
  FE/fe-airbnb/src/components/calendar/CalendarModal.jsx
  FE/fe-airbnb/src/components/calendar/Day.tsx
  FE/fe-airbnb/src/components/calendar/DayNames.jsx
  FE/fe-airbnb/src/components/headcount/Counter.tsx
  FE/fe-airbnb/src/components/headcount/HeadCount.tsx
  FE/fe-airbnb/src/components/headcount/HeadCountModal.tsx
  FE/fe-airbnb/src/components/headcount/HeadCountTypes.tsx
  FE/fe-airbnb/src/components/hotelList/HotelInfo.tsx
  FE/fe-airbnb/src/components/hotelList/HotelInfoList.tsx
  FE/fe-airbnb/src/components/hotelList/hotelInfoTypes.ts
  FE/fe-airbnb/src/components/map/Map.tsx
  FE/fe-airbnb/src/components/map/mockupCoordinates.js
  FE/fe-airbnb/src/components/pages/MainPage.tsx
  FE/fe-airbnb/src/components/pages/ReservationPage.tsx
  FE/fe-airbnb/src/components/price/PriceChart.tsx
  FE/fe-airbnb/src/components/price/PriceModal.tsx
  FE/fe-airbnb/src/components/price/RangeSlider.jsx
  FE/fe-airbnb/src/components/price/sampleData.ts
  FE/fe-airbnb/src/components/searchBar/SearchBar.jsx
  FE/fe-airbnb/src/components/searchBar/SearchBar.tsx
  FE/fe-airbnb/src/components/searchBar/SearchBarBtn.tsx
  FE/fe-airbnb/src/components/searchBar/searchBarTypes.ts
  FE/fe-airbnb/src/icon/minus-circle.svg
  FE/fe-airbnb/src/icon/pause-circle.svg
  FE/fe-airbnb/src/icon/plus-circle-disabled.svg
  FE/fe-airbnb/src/icon/plus-circle.svg
  FE/fe-airbnb/yarn.lock
Labels: review-fe

#73 [ team-11 / FE ] 타입스크립트 적용
  FE/package-lock.json
  FE/package.json
  FE/src/App.tsx
  FE/src/components/Footer/Footer.tsx
  FE/src/components/Header/Header.tsx
  FE/src/components/Header/Logo.tsx
  FE/src/components/Header/Menu.tsx
  FE/src/components/Header/MyPage.tsx
  FE/src/components/Header/SearchBar/CloseButton.tsx
  FE/src/components/Header/SearchBar/Period/Calendar/Calendar.tsx
  FE/src/components/Header/SearchBar/Period/Calendar/Day.tsx
  FE/src/components/Header/SearchBar/Period/CalendarModal.tsx
  FE/src/components/Header/SearchBar/Period/Period.tsx
  FE/src/components/Header/SearchBar/Personnel/Personnel.tsx
  FE/src/components/Header/SearchBar/Personnel/PersonnelModal.tsx
  FE/src/components/Header/SearchBar/Price/Price.tsx
  FE/src/components/Header/SearchBar/Price/PriceModal.tsx
  FE/src/components/Header/SearchBar/Price/Slider.tsx
  FE/src/components/Header/SearchBar/SearchBar.tsx
  FE/src/components/Header/SearchBar/SearchButton.tsx
  FE/src/components/Main/AnyWhere.tsx
  FE/src/components/Main/Main.tsx
  FE/src/components/Main/NearTravel.tsx
  FE/src/components/Result/Houses/House.tsx
  FE/src/components/Result/Houses/Houses.tsx
  FE/src/components/Result/Map.tsx
  FE/src/components/Result/Modal.tsx
  FE/src/components/Result/ModalCost.tsx
  FE/src/components/Result/ModalInfo.tsx
  FE/src/components/Result/Result.tsx
  FE/src/components/Root.tsx
  FE/src/config/GlobalStyle.tsx
  FE/src/config/ResultContextProvider.tsx
  FE/src/config/SearchBarContextProvider.tsx
  FE/src/json/data.json
  FE/src/react-app-env.d.ts
  FE/src/util/parseDate.js
  FE/tsconfig.json
Labels: review-fe

#76 [Team 20 FE Jenny Tami ] 프로젝트 완성 ( OAuth , 지도 API , 최적화 )
  FE/airbnb-fe/package-lock.json
  FE/airbnb-fe/package.json
  FE/airbnb-fe/public/index.html
  FE/airbnb-fe/src/App.js
  FE/airbnb-fe/src/components/Atoms/Modal/CheckModal/CalendarCarousel/Calendar.jsx
  FE/airbnb-fe/src/components/Atoms/Modal/CheckModal/CalendarCarousel/SingleCalendar.jsx
  FE/airbnb-fe/src/components/Atoms/Modal/CheckModal/CalendarCarousel/createMonthArray.js
  FE/airbnb-fe/src/components/Atoms/Modal/PeopleModal/PeopleCard.jsx
  FE/airbnb-fe/src/components/Atoms/Search/Check/index.jsx
  FE/airbnb-fe/src/components/Atoms/Search/People/index.jsx
  FE/airbnb-fe/src/components/Atoms/Search/Price/index.jsx
  FE/airbnb-fe/src/components/Atoms/Search/SearchBtn/index.jsx
  FE/airbnb-fe/src/components/Atoms/Search/index.jsx
  FE/airbnb-fe/src/components/Atoms/buttons/CloseBtn.jsx
  FE/airbnb-fe/src/components/Atoms/icons/AccountIcon.jsx
  FE/airbnb-fe/src/components/Atoms/icons/AirbnbIcon.jsx
  FE/airbnb-fe/src/components/Atoms/icons/Heart.jsx
  FE/airbnb-fe/src/components/Atoms/icons/MenuIcon.jsx
  FE/airbnb-fe/src/components/Atoms/icons/RatingStar.jsx
  FE/airbnb-fe/src/components/Callback.jsx
  FE/airbnb-fe/src/components/Home/HeroSection/Header/AccountMenu/AccountModal.jsx
  FE/airbnb-fe/src/components/Home/HeroSection/Header/AccountMenu/LoginPage.jsx
  FE/airbnb-fe/src/components/Home/HeroSection/Header/AccountMenu/index.jsx
  FE/airbnb-fe/src/components/Home/HeroSection/Header/NavRadio/Activity.jsx
  FE/airbnb-fe/src/components/Home/HeroSection/Header/NavRadio/Online.jsx
  FE/airbnb-fe/src/components/Home/HeroSection/Header/NavRadio/Room.jsx
  FE/airbnb-fe/src/components/Home/HeroSection/Header/index.jsx
  FE/airbnb-fe/src/components/Home/HeroSection/index.jsx
  FE/airbnb-fe/src/components/Home/TourSection/CityTour/index.jsx
  FE/airbnb-fe/src/components/Home/TourSection/RoomTour/index.jsx
  FE/airbnb-fe/src/components/Home/TourSection/index.jsx
  FE/airbnb-fe/src/components/Loader.jsx
  FE/airbnb-fe/src/components/Reservation/ReservationHeader/index.jsx
  FE/airbnb-fe/src/components/Reservation/ReservationMain/AvailableRoom/AvailableRoomCard.jsx
  FE/airbnb-fe/src/components/Reservation/ReservationMain/AvailableRoom/index.jsx
  FE/airbnb-fe/src/components/Reservation/ReservationMain/RoomMap/index.jsx
  FE/airbnb-fe/src/components/Reservation/ReservationMain/RoomPayModal/index.jsx
  FE/airbnb-fe/src/components/Reservation/ReservationMain/index.jsx
  FE/airbnb-fe/src/components/Reservation/index.jsx
  FE/airbnb-fe/src/components/utils/API.js
  FE/airbnb-fe/src/components/utils/getRegex.js
  FE/airbnb-fe/src/components/utils/mock/room-card.json
  FE/airbnb-fe/src/components/utils/reducer/calendarReducer.js
  FE/airbnb-fe/src/components/utils/reducer/payModalReducer.js
  FE/airbnb-fe/src/components/utils/reducer/peopleReducer.js
  FE/airbnb-fe/src/components/utils/reducer/priceReducer.js
  FE/airbnb-fe/src/components/utils/theme.js
  FE/airbnb-fe/yarn.lock
  README.md
Labels: review-fe

#78 [Team 06_FE_Q ] 프로젝트 마무리
  fe/.env
  fe/.gitignore
  fe/config-overrides.js
  fe/package-lock.json
  fe/package.json
  fe/public/index.html
  fe/public/pause-circle.svg
  fe/public/thumbnail.png
  fe/src/App.tsx
  fe/src/components/Header/Calender/Calendar.tsx
  fe/src/components/Header/Calender/CalendarWrap.tsx
  fe/src/components/Header/Calender/Day.tsx
  fe/src/components/Header/Nav/Form.tsx
  fe/src/components/Header/Nav/Menu.tsx
  fe/src/components/Header/Nav/Nav.tsx
  fe/src/components/Header/PriceChart/ChartModal.tsx
  fe/src/components/Header/PriceChart/Graph.tsx
  fe/src/components/Header/PriceChart/testPrice.js
  fe/src/components/Header/ProfileMenu/Login.tsx
  fe/src/components/Header/ProfileMenu/Profile.tsx
  fe/src/components/Header/ProfileMenu/queryString.d.ts
  fe/src/components/Header/Search/Count.tsx
  fe/src/components/Header/Search/Date.tsx
  fe/src/components/Header/Search/Fare.tsx
  fe/src/components/Header/Search/GuestItem.tsx
  fe/src/components/Header/Search/GuestModal.tsx
  fe/src/components/Header/Search/Guests.tsx
  fe/src/components/Header/Search/SearchBar.tsx
  fe/src/components/Header/Search/SearchButton.tsx
  fe/src/components/SearchResult/Header.tsx
  fe/src/components/SearchResult/MiniSearchBar.tsx
  fe/src/components/SearchResult/accommodation/Accommodation.tsx
  fe/src/components/SearchResult/accommodation/RoomInMap.tsx
  fe/src/components/SearchResult/map/Map.tsx
  fe/src/components/SearchResult/types.ts
  fe/src/components/common/Loading.tsx
  fe/src/pages/LandingPage.tsx
  fe/src/pages/SearchResult.tsx
  fe/src/recoil/atoms/calendarState.ts
  fe/src/recoil/atoms/date.ts
  fe/src/recoil/atoms/guests.ts
  fe/src/recoil/atoms/modalState.ts
  fe/src/recoil/atoms/price.ts
  fe/src/recoil/atoms/searchResult.ts
  fe/src/recoil/types/dateType.ts
  fe/src/styles/theme.js
  fe/src/utils/query.ts
  fe/tsconfig.json
  fe/tsconfig.path.json
  fe/yarn.lock
Labels: review-fe

#79 [FE][TEAM-01-Kyle] 에어비엔비 최종본
  FE/airbnb/package-lock.json
  FE/airbnb/package.json
  FE/airbnb/public/index.html
  FE/airbnb/src/App.tsx
  FE/airbnb/src/components/calendar/CalendarDate.tsx
  FE/airbnb/src/components/calendar/CalendarHeader.tsx
  FE/airbnb/src/components/commonComponents/ConditionalLink.tsx
  FE/airbnb/src/components/header/Header.tsx
  FE/airbnb/src/components/header/HoverBlock.tsx
  FE/airbnb/src/components/header/form/FormCheckIn.tsx
  FE/airbnb/src/components/header/form/FormCheckOut.tsx
  FE/airbnb/src/components/header/form/FormColumn.tsx
  FE/airbnb/src/components/header/form/FormGuest.tsx
  FE/airbnb/src/components/header/form/FormLocation.tsx
  FE/airbnb/src/components/header/form/FormPrice.tsx
  FE/airbnb/src/components/header/form/calendar/FormCalendar.tsx
  FE/airbnb/src/components/header/form/guestToggle/GuestColumn.tsx
  FE/airbnb/src/components/header/form/priceBar/PriceBar.tsx
  FE/airbnb/src/components/header/form/priceBar/PriceChart.tsx
  FE/airbnb/src/components/header/tab/HeaderTab.tsx
  FE/airbnb/src/components/map/Map.tsx
  FE/airbnb/src/components/map/MapLabel.tsx
  FE/airbnb/src/components/reserveHeader/ReserveHeader.tsx
  FE/airbnb/src/components/reserveHeader/ReserveHeaderForm.tsx
  FE/airbnb/src/components/reservePageSkeleton/MapSkeleton.tsx
  FE/airbnb/src/components/reservePageSkeleton/ReserveListSkeleton.tsx
  FE/airbnb/src/components/reservePageSkeleton/ReserveSkeleton.tsx
  FE/airbnb/src/components/reserveRoomList/ReserveEmptyRooms.tsx
  FE/airbnb/src/components/reserveRoomList/ReserveRoom.tsx
  FE/airbnb/src/components/reserveRoomList/ReserveRoomList.tsx
  FE/airbnb/src/components/reserveRoomList/ReserveRoomPrice.tsx
  FE/airbnb/src/components/reserveRoomList/ReserveRoomsSection.tsx
  FE/airbnb/src/components/reserveRoomList/reserveForm/ReserveBtn.tsx
  FE/airbnb/src/components/reserveRoomList/reserveForm/ReserveForm.tsx
  FE/airbnb/src/components/reserveRoomList/reserveForm/ReserveFormHeader.tsx
  FE/airbnb/src/components/reserveRoomList/reserveForm/ReserveFormInfo.tsx
  FE/airbnb/src/components/reserveRoomList/reserveForm/ReserveFromPrice.tsx
  FE/airbnb/src/hooks/useToggle.ts
  FE/airbnb/src/index.css
  FE/airbnb/src/pages/ReservePage.tsx
  FE/airbnb/src/recoil/headerAtom.ts
  FE/airbnb/src/recoil/reserveRoomAtom.ts
  FE/airbnb/src/recoilStore/calendarAtom.ts
  FE/airbnb/src/recoilStore/headerAtom.ts
  FE/airbnb/src/recoilStore/reserveRoomAtom.ts
  FE/airbnb/src/recoilStore/roomSampleData.ts
  FE/airbnb/src/util/api.ts
  FE/airbnb/src/util/calendarUtils.tsx
  FE/airbnb/src/util/tsUtils.ts
  FE/airbnb/src/util/util.js
  FE/airbnb/src/util/utilStyles.ts
Labels: review-fe

#80 [Team22][FE - Daisy, Dico] Airbnb Ver. 6월 5일 (To be continued...)
  backend/server/spring-log.txt
  frontend/src/App.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Header/Login.tsx
  frontend/src/components/Header/LoginModal.tsx
  frontend/src/components/Header/MiniHeader.tsx
  frontend/src/components/Header/Navigator.tsx
  frontend/src/components/Reservation/Reservation.tsx
  frontend/src/components/Reservation/ReservationStyle.tsx
  frontend/src/components/RoomList/RoomCard.tsx
  frontend/src/components/RoomList/RoomList.tsx
  frontend/src/components/SearchBar/Calendar/Calendar.tsx
  frontend/src/components/SearchBar/Calendar/CalendarModal.tsx
  frontend/src/components/SearchBar/Calendar/MonthlyCalendar.tsx
  frontend/src/components/SearchBar/Calendar/Old.md
  frontend/src/components/SearchBar/Guests/GuestStyles.tsx
  frontend/src/components/SearchBar/MiniSearchBar.tsx
  frontend/src/components/SearchBar/RoomPrice/PriceGraph.tsx
  frontend/src/components/SearchBar/RoomPrice/PriceRange.tsx
  frontend/src/components/SearchBar/RoomPrice/Prices.json
  frontend/src/components/SearchBar/RoomPrice/RoomPriceModal.tsx
  frontend/src/components/SearchBar/SearchBar.tsx
  frontend/src/components/SearchBar/SearchFilter.jsx
  frontend/src/components/SearchBar/hooks/useFetch.tsx
  frontend/src/components/common/Responsive.jsx
  frontend/src/components/pages/LoadingPage.tsx
  frontend/src/components/pages/MainPage.tsx
  frontend/src/components/pages/ResultPage.tsx
  frontend/src/etc./LoadingPage copy.md
  frontend/src/etc./RoomCard copy.md
  frontend/src/recoil/AtomTypes.tsx
  frontend/src/recoil/Atoms.tsx
  frontend/src/util/API.js
  frontend/src/util/textContent.js
Labels: review-fe

#81 [Team2_FE_eve] 에어비앤비 프로젝트 마무리
  FE/airbnb/.gitignore
  FE/airbnb/public/index.html
  FE/airbnb/src/component/PrimarySection.tsx
  FE/airbnb/src/component/header/LandingPageHeader.tsx
  FE/airbnb/src/component/header/Logo.tsx
  FE/airbnb/src/component/header/MyPage.tsx
  FE/airbnb/src/component/header/MyPageModal.tsx
  FE/airbnb/src/component/header/SearchPageHeader.tsx
  FE/airbnb/src/component/searchBar/Fare.tsx
  FE/airbnb/src/component/searchBar/Guest.tsx
  FE/airbnb/src/component/searchBar/Period.tsx
  FE/airbnb/src/component/searchBar/SearchBar.tsx
  FE/airbnb/src/component/searchBar/SearchBtn.tsx
  FE/airbnb/src/component/searchBar/calendar/Calendar.tsx
  FE/airbnb/src/component/searchBar/calendar/CalendarModal.tsx
  FE/airbnb/src/component/searchBar/calendar/Day.tsx
  FE/airbnb/src/component/searchBar/calendar/getCalendarData.ts
  FE/airbnb/src/component/searchBar/fareChart/ChartCanvas.tsx
  FE/airbnb/src/component/searchBar/fareChart/FareModal.tsx
  FE/airbnb/src/component/searchBar/fareChart/FareRangeSlider.tsx
  FE/airbnb/src/component/searchBar/fareChart/SuspenseFareModal.tsx
  FE/airbnb/src/component/searchBar/guestList/GuestModal.tsx
  FE/airbnb/src/component/searchBar/modalFunctions.ts
  FE/airbnb/src/component/searchResult/AccommodationCard.tsx
  FE/airbnb/src/component/searchResult/AccommodationList.tsx
  FE/airbnb/src/component/searchResult/Map.tsx
  FE/airbnb/src/pages/SearchResultPage.tsx
  FE/airbnb/src/state/atoms/calendarAtoms.ts
  FE/airbnb/src/state/atoms/fareAtoms.ts
  FE/airbnb/src/state/atoms/guestAtoms.ts
  FE/airbnb/src/state/atoms/positionAtoms.ts
  FE/airbnb/src/state/atoms/searchResultAtoms.ts
  FE/airbnb/src/state/selectors/priceFetch.ts
  FE/airbnb/src/state/selectors/searchDetail.ts
  FE/airbnb/src/state/selectors/searchQuery.ts
  FE/airbnb/src/styles/theme.ts
  FE/airbnb/src/variable.ts
Labels: review-fe

#83 [FE_Junami] 마무리 PR
  frontend/.env
  frontend/public/index.html
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/Interface.tsx
  frontend/src/bg.jpg
  frontend/src/components/header/CenterMenu.tsx
  frontend/src/components/header/Header.tsx
  frontend/src/components/header/Login.tsx
  frontend/src/components/header/Logo.tsx
  frontend/src/components/header/UserInfo.tsx
  frontend/src/components/reservation/Reservation.tsx
  frontend/src/components/searchBar/SearchBar.tsx
  frontend/src/components/searchBar/date/Calendar.tsx
  frontend/src/components/searchBar/date/CheckIn.tsx
  frontend/src/components/searchBar/date/CheckOut.tsx
  frontend/src/components/searchBar/date/Date.tsx
  frontend/src/components/searchBar/date/ModalCalendar.tsx
  frontend/src/components/searchBar/fee/Fee.tsx
  frontend/src/components/searchBar/fee/Graph.tsx
  frontend/src/components/searchBar/fee/ModalFee.tsx
  frontend/src/components/searchBar/fee/Slider.tsx
  frontend/src/components/searchBar/personnel/ModalPersonnel.tsx
  frontend/src/components/searchBar/personnel/Personnel.tsx
  frontend/src/components/searchBar/place/ModalPlace.tsx
  frontend/src/components/searchBar/place/Place.tsx
  frontend/src/components/searchBar/searchBtn/SearchBtn.tsx
  frontend/src/components/searchResult/HouseList.tsx
  frontend/src/components/searchResult/Map.tsx
  frontend/src/components/searchResult/MiniSearchBar.tsx
  frontend/src/components/searchResult/SearchResult.tsx
  frontend/src/components/searchResult/WishListToggle.tsx
  frontend/src/customHook/atoms.tsx
  frontend/src/customHook/axiosAPI.tsx
  frontend/src/customHook/useAxios.tsx
  frontend/src/customHook/useDateInfo.tsx
  frontend/src/customHook/useModalCtrlArray.tsx
  frontend/src/customHook/useXclick.tsx
  frontend/src/index.css
  frontend/src/index.tsx
  frontend/src/style/GlobalStyle.tsx
  frontend/src/style/Loading.tsx
  frontend/src/style/Theme.tsx
Labels: review-fe

#77 [team-03 iOS Elly] 컨트롤러 간 데이터 통신, 인원수 조정 MVVM 패턴 적용
  iOS/airbnb.xcodeproj/project.pbxproj
  iOS/airbnb/Container/CalendarPicker/CalendarViewController.swift
  iOS/airbnb/Container/CalendarPicker/Model/CalendarDateCalculator.swift
  iOS/airbnb/Container/CalendarPicker/Model/CalenderCollectionDataSource.swift
  iOS/airbnb/Container/CalendarPicker/Model/Day.swift
  iOS/airbnb/Container/CalendarPicker/Model/MonthMetadata.swift
  iOS/airbnb/Container/CalendarPicker/View/CalendarDateCell.swift
  iOS/airbnb/Container/CalendarPicker/View/CalendarHeader.swift
  iOS/airbnb/Container/CalendarPicker/ViewModel/CalendarViewModel.swift
  iOS/airbnb/Container/ContainerViewController.swift
  iOS/airbnb/Container/FooterTable/FooterTableViewCell.swift
  iOS/airbnb/Container/FooterTable/FooterTableViewDataSource.swift
  iOS/airbnb/Container/People/Model/CounterState.swift
  iOS/airbnb/Container/People/PersonCountViewController.swift
  iOS/airbnb/Container/People/View/PersonTableViewCell.swift
  iOS/airbnb/Container/People/View/PersonTableViewCell.xib
  iOS/airbnb/Container/People/ViewModel/CounterViewModel.swift
  iOS/airbnb/Container/PriceGraph/PriceGraphView.swift
  iOS/airbnb/Container/PriceGraph/PriceViewController.swift
  iOS/airbnb/Container/SelectInfoDelegate.swift
  iOS/airbnb/Extension/CaseIterable+next.swift
  iOS/airbnb/Extension/Date+Extension.swift
  iOS/airbnb/Extension/UIImageView+LoadFromURL.swift
  iOS/airbnb/Extension/UIViewController+storyboard.swift
  iOS/airbnb/FooterTable/FooterTableViewController.swift
  iOS/airbnb/Login/LoginCoordinator.swift
  iOS/airbnb/Login/LoginViewController.swift
  iOS/airbnb/Network/APIService.swift
  iOS/airbnb/Network/APIServiceError.swift
  iOS/airbnb/Network/EndPoint.swift
  iOS/airbnb/Network/NetworkDispatcher.swift
  iOS/airbnb/Network/NetworkError.swift
  iOS/airbnb/Network/PriceNetworkDispatcher.swift
  iOS/airbnb/Network/Responses.swift
  iOS/airbnb/Network/TravelListAPI.swift
  iOS/airbnb/Network/TravelNetworkDispatcher.swift
  iOS/airbnb/Search/ContainerViewController.swift
  iOS/airbnb/Search/HotelListViewController.swift
  iOS/airbnb/Search/Model/NearPlace.swift
  iOS/airbnb/Search/Search.storyboard
  iOS/airbnb/Search/SearchCoordinator.swift
  iOS/airbnb/Search/SearchViewController.swift
  iOS/airbnb/Search/TravelListViewController.swift
  iOS/airbnb/Search/View/NearPlaceCell.swift
  iOS/airbnb/Storyboarded.swift
  iOS/airbnb/WishList/WishListCoordinator.swift
  iOS/airbnb/WishList/WishListViewController.swift
Labels: review-iOS
